Repository cerbos/cerbos, pull requests merged in 2021-09, with the labels that each got.

#271 docs: Add link to Java SDK
  docs/modules/api/pages/index.adoc
Labels: documentation

#270 enhancement: Support h2c
  NOTICE.txt
  client/client_test.go
  go.mod
  internal/server/server.go
  internal/server/server_test.go
Labels: enhancement

#272 docs: Add v0.6.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.6.0.adoc
Labels: documentation, chore

#265 chore: Use admin client in decisions subcommand
  cmd/cerbosctl/audit/audit.go
  cmd/cerbosctl/decisions/decisions.go
  cmd/cerbosctl/internal/definitions.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/main.go
Labels: chore

#275 docs: Update references to cerbosctl
  docs/modules/cli/nav.adoc
  docs/modules/cli/pages/ctl.adoc
Labels: documentation

#276 enhancement: Add version info while using make install
  Makefile
Labels: enhancement

#269 enhancement: List policies endpoint added to Admin API
  NOTICE.txt
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  client/admin.go
  client/admin_test.go
  cmd/cerbosctl/audit/audit.go
  cmd/cerbosctl/decisions/decisions.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/list/list.go
  cmd/cerbosctl/main.go
  go.mod
  go.sum
  internal/compile/manager_test.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/model.go
  internal/storage/db/internal/tests.go
  internal/storage/db/mysql/mysql_test.go
  internal/storage/db/sqlite3/schema.sql
  internal/storage/db/store.go
  internal/storage/disk/disk.go
  internal/storage/disk/index/builder_test.go
  internal/storage/disk/index/codegencache.go
  internal/storage/disk/index/index.go
  internal/storage/git/store.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/svc/playground_svc.go
  internal/test/mocks/Index.go
  internal/test/mocks/MutableStore.go
  internal/test/mocks/Store.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#293 enhancement: Strict configuration
  .chglog/CHANGELOG.tpl.adoc
  .chglog/config.yml
  NOTICE.txt
  cmd/cerbos/server/server.go
  go.mod
  internal/audit/conf.go
  internal/audit/conf_test.go
  internal/audit/log.go
  internal/config/config.go
  internal/config/config_test.go
  internal/server/server.go
  internal/storage/conf.go
  internal/storage/store.go
  internal/test/mocks/Store.go
Labels: enhancement

#296 docs: Preserve older versions
  .github/actions/antora-docs/action.yaml
  docs/antora-playbook.yml
  docs/build.sh
  hack/scripts/prep-release.sh
  netlify.toml
Labels: documentation

#308 docs: Update tutorial tests and other improvements
  README.md
  docs/modules/policies/nav.adoc
  docs/modules/policies/pages/compile.adoc
  docs/modules/tutorials/examples/photo-share/tests/album_object_test.yaml
  docs/modules/tutorials/examples/photo-share/tests/album_object_tests.yaml
  docs/modules/tutorials/pages/photo-share/index.adoc
Labels: documentation

#314 chore(ci): Publish docs on commit to trunk
  .github/workflows/snaphot.yaml
  docs/antora-playbook.yml
  docs/antora.yml
  docs/build.sh
  hack/scripts/prep-release.sh
  netlify.toml
Labels: ci, chore

#309 enhancement: Ignore invalid test suites
  internal/test/testdata/verify/invalid_fixture/suite_test.yaml
  internal/test/testdata/verify/invalid_fixture/testdata/principals.yaml
  internal/test/testdata/verify/invalid_test/invalid_test.yaml
  internal/test/testdata/verify/invalid_test/suite_test.yaml
  internal/test/testdata/verify/valid/empty_test.yaml
  internal/test/testdata/verify/valid/suite_test.yaml
  internal/test/testdata/verify/valid/testdata/principals.yaml
  internal/test/testdata/verify/valid/testdata/resources.yaml
  internal/verify/test_fixture.go
  internal/verify/verify.go
  internal/verify/verify_test.go
Labels: enhancement

#315 chore(release): Add 0.7.0 release notes
  .goreleaser-ci.yml
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.7.0.adoc
Labels: chore, release

#317 chore(ci): Toggle docs author mode during release
  hack/scripts/prep-release.sh
Labels: ci, chore

#316 enhancement: Allow intermingling of tests with policies
  internal/storage/disk/index/builder.go
  internal/test/testdata/index/intermingled_test_files.yaml
  internal/util/filesystem.go
  internal/verify/test_fixture.go
  internal/verify/test_fixture_test.go
  internal/verify/verify.go
  internal/verify/verify_test.go
Labels: enhancement

#313 enhancement: Add filter options to the list policies method of the admin API
  NOTICE.txt
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/public/cerbos/request/v1/request.proto
  client/admin.go
  client/model.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/list/list.go
  docs/modules/cli/pages/ctl.adoc
  go.mod
  go.sum
  internal/svc/admin_svc.go
  internal/svc/helpers.go
  internal/test/mocks/Store.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#326 docs: Document how to obtain gRPC stubs
  docs/modules/api/pages/index.adoc
Labels: documentation

#327 enhancement: Functions for working with hierarchies
  docs/modules/policies/pages/conditions.adoc
  internal/codegen/cel_lib.go
  internal/codegen/cel_lib_test.go
  internal/codegen/cel_types.go
  internal/test/testdata/cel_eval/hierarchy_funcs.yaml
Labels: enhancement
