Repository cerbos/cerbos, pull requests merged in 2021-12, with the labels that each got.

#473 chore(refactor): Change signature of LoadSchema
  internal/compile/manager_test.go
  internal/schema/loader.go
  internal/schema/loader_test.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/index/builder.go
  internal/storage/index/index.go
  internal/storage/index/schema.go
  internal/storage/store.go
  internal/test/mocks/Index.go
Labels: refactoring

#470 enhancement: schema support for db stores
  NOTICE.txt
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.validate.go
  api/genpb/cerbos/schema/v1/schema_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/schema/v1/schema.proto
  api/public/cerbos/svc/v1/svc.proto
  go.mod
  internal/compile/manager_test.go
  internal/schema/schema_test.go
  internal/server/server_test.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/model.go
  internal/storage/db/internal/tests.go
  internal/storage/db/mysql/schema.sql
  internal/storage/db/postgres/schema.sql
  internal/storage/db/sqlite3/schema.sql
  internal/storage/db/store.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/index/index.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/svc/list.go
  internal/test/mocks/Index.go
  internal/test/test.go
  internal/test/testdata/server/admin/add_or_update_policy/case_00.yaml
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#476 fix: Make auxData optional in the OpenAPI example
  api/genpb/cerbos/request/v1/request.pb.go
  api/public/cerbos/request/v1/request.proto
  conf.default.yaml
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: bug

#479 chore(deps): Bump github.com/opencontainers/runc from 1.0.2 to 1.0.3
  NOTICE.txt
  go.mod
  go.sum
Labels: chore

#481 enhancement: Add schema event handling to git store
  internal/storage/git/store.go
  internal/storage/git/store_test.go
Labels: enhancement

#478 chore(refactor): refactor the API endpoints for schemas
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.validate.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/schema/v1/schema.proto
  api/public/cerbos/svc/v1/svc.proto
  internal/compile/manager_test.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/tests.go
  internal/storage/db/store.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/index/index.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/svc/list.go
  internal/test/mocks/Index.go
  internal/test/test.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: refactoring

#482 chore(test): Add test for schema events to blob store
  internal/storage/blob/store_test.go
Labels: testing, chore

#483 docs: Add docs for schema Admin API services
  docs/modules/api/pages/admin_api.adoc
Labels: documentation

#486 docs: Make the Admin API docs follow a consistent style
  docs/modules/api/pages/admin_api.adoc
  docs/modules/policies/pages/schemas.adoc
Labels: documentation

#488 enhancement: Log the number of policies found on startup
  internal/storage/index/builder.go
Labels: enhancement

#490 docs: Add schema example to photo-share tutorial
  cmd/cerbos/compile/compile.go
  docs/modules/tutorials/examples/photo-share/policies/01_apatr_common_roles.yaml
  docs/modules/tutorials/examples/photo-share/policies/02_album_resource.yaml
  docs/modules/tutorials/pages/photo-share/index.adoc
Labels: documentation

#499 chore(ci): Only generate NOTICE during a release
  .github/workflows/dependabot.yaml
  Makefile
  hack/scripts/prep-release.sh
Labels: ci, chore

#502 chore: Fix schema cache and blob store timeout
  internal/policy/policy.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/storage/blob/cloner.go
  internal/storage/store.go
Labels: chore

#503 chore(release): Add 0.11.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.11.0.adoc
Labels: chore

#509 chore(refactor): Fix list policies endpoint returning error message
  internal/svc/admin_svc.go
Labels: refactoring

#511 chore(ci): Disable patch version updates for AWS SDK
  .github/dependabot.yml
Labels: ci, chore

#513 chore(test): Extend test templates and refactor admin service tests
  internal/test/template.go
  internal/test/test.go
  internal/test/testdata/server/admin/add_or_update_policy/case_00.yaml
  internal/test/testdata/server/playground/evaluate/pge_case_00.yaml
  internal/test/testdata/server/playground/evaluate/pge_case_01.yaml
  internal/test/testdata/server/playground/evaluate/pge_case_02.yaml
  internal/test/testdata/server/playground/evaluate/pge_invalid_case_00.yaml
  internal/test/testdata/server/playground/evaluate/pge_invalid_case_02.yaml
  internal/test/testdata/server/playground/proxy/pgp_crb_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crb_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_crb_invalid_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crb_invalid_case_02.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_case_02.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_invalid_case_00.yaml
  internal/test/testdata/server/playground/validate/pgv_case_00.yaml
  internal/test/testdata/server/playground/validate/pgv_invalid_case_00.yaml
Labels: testing, chore

#515 chore(deps): Bump modernc.org/sqlite from 1.14.2 to 1.14.3
  go.mod
  go.sum
Labels: ci, chore

#520 chore(deps): Bump github.com/opencontainers/runc from 1.0.2 to 1.0.3
  go.mod
  go.sum
Labels: chore

#522 fix: Detect files with multiple policies
  internal/policy/io_test.go
  internal/server/server_test.go
  internal/test/testdata/index/multiple_policies_per_file.yaml
  internal/test/testdata/policy_formats/multiple_policies.yaml
  internal/test/testdata/server/playground/evaluate/pge_invalid_case_01.yaml
  internal/test/testdata/server/playground/validate/pgv_invalid_case_01.yaml
  internal/util/serdeio.go
  internal/util/serdeio_test.go
  internal/util/testdata/invalid.yaml
  internal/util/testdata/multiple_json.json
  internal/util/testdata/multiple_yaml1.yaml
  internal/util/testdata/multiple_yaml2.yaml
  internal/util/testdata/single_json.json
  internal/util/testdata/single_yaml.yaml
Labels: bug

#507 docs: Generate full configuration overview from code
  Makefile
  NOTICE.txt
  docs/modules/configuration/pages/index.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  go.mod
  go.sum
  hack/tools/confdocs/confdocs.go
  hack/tools/confdocs/generator.go.tmpl
  internal/audit/conf.go
  internal/audit/local/conf.go
  internal/auxdata/conf.go
  internal/engine/conf.go
  internal/observability/tracing/conf.go
  internal/schema/conf.go
  internal/server/conf.go
  internal/storage/blob/conf.go
  internal/storage/conf.go
  internal/storage/db/mysql/conf.go
  internal/storage/db/postgres/conf.go
  internal/storage/db/sqlite3/conf.go
  internal/storage/disk/conf.go
  internal/storage/git/conf.go
  internal/storage/store.go
Labels: documentation, tooling

#524 chore(perf): Fix struct field alignment
  .golangci.yaml
  client/client.go
  client/model.go
  cmd/cerbos/server/server.go
  cmd/cerbosctl/internal/flags.go
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/conf.go
  internal/audit/id.go
  internal/audit/local/badgerdb.go
  internal/audit/local/collector.go
  internal/auxdata/conf.go
  internal/compile/compile.go
  internal/compile/errors.go
  internal/config/config.go
  internal/config/config_test.go
  internal/engine/ast.go
  internal/engine/engine.go
  internal/engine/planner.go
  internal/engine/trace.go
  internal/observability/tracing/conf.go
  internal/policy/policy.go
  internal/schema/schema.go
  internal/server/conf.go
  internal/storage/blob/conf.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/model.go
  internal/storage/db/mysql/conf.go
  internal/storage/db/postgres/conf.go
  internal/storage/disk/conf.go
  internal/storage/disk/dirwatch.go
  internal/storage/git/conf.go
  internal/storage/index/builder.go
  internal/storage/index/index.go
  internal/storage/store.go
  internal/storage/subscriptionmgr.go
  internal/svc/admin_svc.go
  internal/test/test.go
  internal/verify/test_fixture_test.go
  schema/schema.go
Labels: chore, refactoring

#526 docs: Upgrade to DocSearch v3
  docs/supplemental-ui/partials/footer-content.hbs
  docs/supplemental-ui/partials/head-meta.hbs
  docs/supplemental-ui/partials/header-content.hbs
Labels: documentation

#530 chore(lint): Enable more linters
  .golangci.yaml
  client/credentials.go
  internal/storage/store.go
Labels: ci, chore

#531 enhancement: Switch from Distroless to scratch
  Dockerfile
Labels: enhancement

#516 enhancement(refactor)!: Refactor policy Admin API endpoints
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  client/admin.go
  client/model.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/list/list.go
  docs/modules/cli/pages/ctl.adoc
  go.mod
  go.sum
  internal/compile/manager_test.go
  internal/namer/namer.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/funcs.go
  internal/storage/db/internal/funcs_test.go
  internal/storage/db/internal/model.go
  internal/storage/db/internal/tests.go
  internal/storage/db/postgres/schema.sql
  internal/storage/db/sqlite3/schema.sql
  internal/storage/db/store.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/index/index.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/svc/helpers.go
  internal/svc/list.go
  internal/test/mocks/Index.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement, refactoring
