Repository cerbos/cerbos, pull requests merged in 2021-08, with the labels that each got.

#226 chore: Add godoc and release badges
  README.md
  client/README.md
Labels: chore

#227 chore(ci): Publish protos to Buf schema registry
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .goreleaser-ci.yml
  docs/modules/api/pages/index.adoc
Labels: chore, ci, documentation

#228 chore: Change docs redirect
  docs/antora-playbook.yml
Labels: chore

#229 chore: Configure docs to support multiple versions
  deploy/charts/cerbos/Chart.yaml
  docs/antora-playbook.yml
  docs/antora.yml
  docs/build.sh
  hack/scripts/prep-release.sh
Labels: chore, documentation

#230 docs: Update index.adoc to fix the results of the test
  docs/modules/tutorials/pages/photo-share/index.adoc
Labels: documentation

#231 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: chore

#240 docs: Add Algolia DocSearch
  docs/supplemental-ui/css/site-extra.css
  docs/supplemental-ui/partials/footer-content.hbs
  docs/supplemental-ui/partials/head-meta.hbs
  docs/supplemental-ui/partials/header-content.hbs
Labels: documentation

#252 chore(deps): Upgrade to Go 1.17
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  CONTRIBUTING.md
  NOTICE.txt
  go.mod
  internal/audit/local/badgerdb_test.go
  internal/storage/db/internal/tests.go
  internal/storage/db/mysql/mysql_test.go
  tools/go.mod
  tools/go.sum
Labels: chore

#253 chore(refactor): Public and private protobufs
  NOTICE.txt
  api/buf.md
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/private/buf.lock
  api/private/buf.yaml
  api/private/cerbos/private/v1/test.proto
  api/public/buf.lock
  api/public/buf.yaml
  api/public/cerbos/audit/v1/audit.proto
  api/public/cerbos/effect/v1/effect.proto
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/policy/v1/policy.proto
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  buf.work.yaml
  go.mod
  go.sum
  internal/test/mocks.go
  internal/test/policy.go
  internal/test/random.go
  internal/test/request.go
  internal/test/test.go
  tools/go.mod
  tools/go.sum
  tools/tools.mk
Labels: chore, refactoring

#254 chore(ci): Update Buf push action
  .github/dependabot.yml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
Labels: ci, chore

#256 chore: Add PlaygroundProxy RPC
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/private/cerbos/private/v1/test.proto
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  internal/server/server_test.go
  internal/svc/playground_svc.go
  internal/test/testdata/server/playground/proxy/pgp_crb_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crb_invalid_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_crs_invalid_case_00.yaml
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature, chore

#257 chore(deps): Bump BadgerDB version to v3.2103.1
  NOTICE.txt
  go.mod
  go.sum
Labels: chore

#260 docs: Update readme
  README.md
Labels: documentation

#223 feature: Add audit to admin client
  Makefile
  client/admin.go
  client/admin_test.go
  client/model.go
  cmd/cerbosctl/audit/audit.go
  cmd/cerbosctl/main.go
Labels: enhancement, sdk

#262 docs: Add v0.5.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.5.0.adoc
Labels: documentation
