Repository cerbos/cerbos, pull requests merged in 2021-10, with the labels that each got.

#325 enhancement: User defined vars
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/public/cerbos/policy/v1/policy.proto
  docs/modules/policies/pages/conditions.adoc
  docs/modules/policies/pages/derived_roles.adoc
  docs/modules/policies/pages/principal_policies.adoc
  docs/modules/policies/pages/resource_policies.adoc
  internal/codegen/cel.go
  internal/codegen/codegen.go
  internal/codegen/rego.go
  internal/compile/compile.go
  internal/compile/conditions.go
  internal/storage/disk/index/index.go
  internal/test/testdata/codegen/valid_resource_policy_01.yaml
  internal/test/testdata/store/derived_roles/derived_roles_02.yaml
  internal/test/testdata/store/principal_policies/policy_01.yaml
  internal/test/testdata/store/resource_policies/policy_01.yaml
  internal/test/testdata/verify/valid/testdata/principals.yaml
  internal/test/testdata/verify/valid/testdata/resources.yaml
  internal/test/testdata/verify/valid/udf_test.yaml
  internal/verify/verify_test.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#331 chore(release): Add 0.8.0 release notes
  docs/modules/policies/pages/conditions.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.8.0.adoc
Labels: chore, release

#334 bug: Rename cors.enabled config key to cors.disabled
  internal/server/conf.go
Labels: bug

#320 enhancement: Add sorting option to the list policies method options
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/public/cerbos/request/v1/request.proto
  client/admin.go
  client/model.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/list/list.go
  docs/modules/cli/pages/ctl.adoc
  internal/svc/admin_svc.go
  internal/svc/list.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#335 chore(refactor): Move CEL code to conditions package
  internal/codegen/cel.go
  internal/codegen/codegen.go
  internal/codegen/rego.go
  internal/compile/conditions.go
  internal/conditions/cel.go
  internal/conditions/cerbos_lib.go
  internal/conditions/cerbos_lib_test.go
  internal/conditions/types/hierarchy.go
  internal/conditions/types/type_adapter.go
Labels: chore, refactoring

#338 docs: Document how to obtain protobuf definitions
  docs/modules/api/pages/index.adoc
Labels: documentation

#345 chore(deps): Bump github.com/containerd/containerd from 1.5.5 to 1.5.7
  NOTICE.txt
  go.mod
  go.sum
Labels: ci, chore

#342 enhancement: Hierarchy function improvements
  docs/modules/policies/pages/conditions.adoc
  internal/conditions/cerbos_lib_test.go
  internal/conditions/types/hierarchy.go
  internal/test/testdata/cel_eval/hierarchy_funcs.yaml
Labels: enhancement
