Repository cerbos/cerbos, pull requests merged in 2021-11, with the labels that each got.

#422 fix: Updates URL to download Cerbos binaries
  docs/modules/ROOT/partials/attributes.adoc
  internal/test/test.go
Labels: bug, documentation

#423 chore(ci): Configure semantic commit prefixes
  .github/semantic.yml
Labels: ci, chore

#420 enhancement: Better errors when disabled services are accessed
  internal/server/middleware.go
  internal/server/server.go
Labels: enhancement

#425 chore(deps): Remove outdated Docker dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: chore

#424 feat: Linux packages
  .goreleaser-ci.yml
  .goreleaser-dev.yml
  Makefile
  deploy/linux/conf/cerbos.yaml
  deploy/linux/scripts/post-install.sh
  deploy/linux/scripts/pre-remove.sh
  deploy/linux/unit/cerbos.service
  docs/modules/ROOT/pages/installation/binary.adoc
  docs/modules/ROOT/partials/attributes.adoc
  docs/modules/deployment/nav.adoc
  docs/modules/deployment/pages/systemd.adoc
Labels: feature

#428 feat: Homebrew formula
  .github/workflows/release.yaml
  .goreleaser-ci.yml
  docs/modules/ROOT/pages/installation/binary.adoc
  tools/go.mod
  tools/go.sum
Labels: feature

#427 chore(ci): Add nightly multi-OS test workflow
  .github/workflows/helm.yaml
  .github/workflows/test-matrix.yaml
  .goreleaser-ci.yml
Labels: ci, chore

#429 chore(ci): Cleanup Goreleaser configuration
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/test-matrix.yaml
  .goreleaser-dev.yml
  .goreleaser.yml
  CONTRIBUTING.md
  Makefile
Labels: ci, chore

#430 chore(ci): Disable test matrix and Windows build
  .github/workflows/test-matrix.yaml
  .goreleaser.yml
Labels: ci, chore

#434 docs: Fix passwordHash in full configuration doc
  docs/modules/configuration/pages/index.adoc
Labels: documentation

#436 chore(ci): Run PR workflow for backports
  .github/workflows/pr-test.yaml
Labels: ci, chore

#435 docs: Generate docs from branches
  docs/antora-playbook.yml
  hack/scripts/prep-release.sh
Labels: documentation

#440 chore(release): Add 0.10.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.10.0.adoc
Labels: chore, release

#442 chore(ci): Update docs branch list during release
  hack/scripts/prep-release.sh
Labels: ci, chore

#443 feat: Support for OpenTelemetry traces
  NOTICE.txt
  cmd/cerbos/server/server.go
  docs/modules/configuration/pages/tracing.adoc
  go.mod
  go.sum
  hack/dev/conf.insecure.yaml
  hack/dev/dev.mk
  internal/engine/engine.go
  internal/engine/evaluator.go
  internal/observability/tracing/attributes.go
  internal/observability/tracing/conf.go
  internal/observability/tracing/tracing.go
  internal/server/server.go
Labels: feature

#445 chore(ci): Add latest tag and remove JFrog
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .goreleaser.yml
Labels: ci, chore

#449 chore(deps): Bump github.com/opencontainers/image-spec from 1.0.1 to 1.0.2
  NOTICE.txt
  go.mod
  go.sum
Labels: chore

#448 feat: Attribute schemas with JSONSchema
  NOTICE.txt
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.validate.go
  api/genpb/cerbos/engine/v1/engine_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.go
  api/genpb/cerbos/schema/v1/schema.pb.validate.go
  api/genpb/cerbos/schema/v1/schema_vtproto.pb.go
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/schema/v1/schema.proto
  client/testutil/server.go
  cmd/cerbos/compile/compile.go
  docs/modules/configuration/pages/index.adoc
  docs/modules/configuration/pages/schema.adoc
  go.mod
  go.sum
  internal/compile/manager_test.go
  internal/engine/engine.go
  internal/engine/engine_test.go
  internal/schema/conf.go
  internal/schema/error.go
  internal/schema/io.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/schema/validate.go
  internal/server/server.go
  internal/server/server_test.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/disk/dirwatch.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/index/builder.go
  internal/storage/store.go
  internal/svc/playground_svc.go
  internal/svc/response.go
  internal/test/test.go
  internal/verify/verify_test.go
  schema/openapiv2/cerbos/schema/v1/schema.swagger.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
  tools/tools.go
Labels: feature

#454 docs: Add tutorials to documentation
  docs/modules/tutorials/assets/images/jwt-token.png
  docs/modules/tutorials/nav.adoc
  docs/modules/tutorials/pages/authentication/auth0/index.adoc
  docs/modules/tutorials/pages/authentication/jwt/index.adoc
  docs/modules/tutorials/pages/authentication/magic/index.adoc
  docs/modules/tutorials/pages/orm/prisma/index.adoc
Labels: documentation

#456 docs(backport): Add tutorials
  docs/modules/tutorials/assets/images/jwt-token.png
  docs/modules/tutorials/nav.adoc
  docs/modules/tutorials/pages/authentication/auth0/index.adoc
  docs/modules/tutorials/pages/authentication/jwt/index.adoc
  docs/modules/tutorials/pages/authentication/magic/index.adoc
  docs/modules/tutorials/pages/orm/prisma/index.adoc
Labels: documentation

#459 chore(ci): Add docs publication workflow
  .github/actions/antora-docs/action.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  hack/scripts/prep-release.sh
Labels: ci, chore

#458 chore(refactor): Schema refactoring pass 1
  .golangci.yaml
  internal/schema/conf.go
  internal/schema/error.go
  internal/schema/io.go
  internal/schema/schema.go
  internal/schema/validate.go
  tools/go.mod
  tools/go.sum
Labels: refactoring

#465 enhancement: Validation errors in audit log
  hack/dev/conf.insecure.yaml
  hack/dev/conf.secure.yaml
  hack/scripts/cover.sh
  internal/engine/engine.go
  internal/engine/engine_test.go
  internal/schema/conf.go
  internal/schema/error.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/svc/playground_svc.go
  internal/test/test.go
  internal/test/testdata/engine_schema_enforcement/reject/case_00.yaml
  internal/test/testdata/engine_schema_enforcement/reject/case_01.yaml
  internal/test/testdata/engine_schema_enforcement/warn/case_00.yaml
  internal/test/testdata/engine_schema_enforcement/warn/case_01.yaml
  internal/test/testdata/schema/case_03.yaml
Labels: enhancement

#461 enhancement: Add store and Admin API services for schema feature
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  docs/modules/configuration/pages/index.adoc
  internal/compile/manager.go
  internal/compile/manager_test.go
  internal/schema/io.go
  internal/schema/schema.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/model.go
  internal/storage/db/internal/tests.go
  internal/storage/db/mysql/schema.sql
  internal/storage/db/postgres/schema.sql
  internal/storage/db/sqlite3/schema.sql
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/test/test.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement
