Repository cerbos/cerbos, pull requests merged in 2022-06, with the labels that each got.

#965 chore(test): Update Minio config in tests
  e2e/run.sh
  internal/storage/blob/tests.go
Labels: testing, chore

#966 enhancement: Allow setting file mode of UDS
  docs/modules/configuration/pages/server.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/server/conf.go
  internal/server/server.go
  tools/go.mod
  tools/go.sum
Labels: enhancement

#973 fix: Cerbosctl version should fail gracefully
  cmd/cerbosctl/version/version.go
Labels: bug

#981 enhancement: Optimise NOT conditions in query planner output
  internal/engine/ast.go
  internal/engine/planner_test.go
  internal/test/testdata/query_planner/suite/donald_duck.yaml
Labels: enhancement

#980 enhancement: Support auto-propagation for traces
  docs/modules/configuration/pages/tracing.adoc
  go.mod
  go.sum
  internal/observability/tracing/conf.go
  internal/observability/tracing/tracing.go
  internal/server/server.go
Labels: enhancement

#982 chore(ci): Publish cerbosctl snapshot container
  .github/workflows/snaphot.yaml
Labels: ci, chore

#989 enhancement: Add store polling metrics
  internal/observability/metrics/metrics.go
  internal/storage/blob/store.go
  internal/storage/db/internal/db.go
  internal/storage/disk/dirwatch.go
  internal/storage/git/store.go
  internal/storage/index/index.go
Labels: enhancement

#990 docs: Add JavaScript SDK link to README
  README.md
Labels: documentation

#994 chore(ci): Parallelize generate and test jobs
  .github/workflows/pr-test.yaml
Labels: ci, chore

#995 enhancement: Cache JWT verification status
  docs/modules/configuration/pages/auxdata.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  go.mod
  go.sum
  internal/auxdata/conf.go
  internal/auxdata/jwt.go
  internal/auxdata/jwt_test.go
Labels: enhancement

#1003 enhancement!: Normalise query plan filterDebug field
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_hashpb.pb.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/private/cerbos/private/v1/test.proto
  internal/engine/ast.go
  internal/engine/planner.go
  internal/engine/planner_test.go
  internal/test/testdata/query_planner_filter/case_00.yaml
  internal/test/testdata/query_planner_filter/case_01.yaml
  internal/test/testdata/query_planner_filter/case_02.yaml
  internal/test/testdata/query_planner_filter/case_03.yaml
  internal/test/testdata/query_planner_filter/case_04.yaml
  internal/test/testdata/query_planner_filter/case_05.yaml
  internal/test/testdata/query_planner_filter/case_06.yaml
  internal/test/testdata/query_planner_filter/case_07.yaml
  internal/test/testdata/query_planner_filter/case_08.yaml
  internal/test/testdata/query_planner_filter/case_09.yaml
  internal/test/testdata/query_planner_filter/case_10.yaml
  internal/test/testdata/query_planner_filter/case_11.yaml
  internal/test/testdata/server/plan_resources/plan_case_00.yaml
  internal/test/testdata/server/plan_resources/plan_case_01_acme.hr.uk.yaml
  internal/test/testdata/server/plan_resources/plan_case_02_acme.hr.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_00.yaml
Labels: enhancement

#1006 docs: Add links to .NET SDK
  README.md
  docs/modules/api/assets/images/dot-net.svg
  docs/modules/api/pages/index.adoc
Labels: documentation

#1007 docs: Specify what happens when multiple rules match
  docs/modules/policies/pages/resource_policies.adoc
Labels: documentation

#1010 enhancement: Allow multiple rules per action in principal policies
  api/genpb/cerbos/runtime/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/runtime/v1/runtime.pb.go
  api/genpb/cerbos/runtime/v1/runtime.pb.validate.go
  api/genpb/cerbos/runtime/v1/runtime_vtproto.pb.go
  api/private/cerbos/runtime/v1/runtime.proto
  internal/compile/compile.go
  internal/engine/evaluator.go
  internal/engine/planner.go
  internal/test/testdata/compile/principal_policy.yaml.golden
  internal/test/testdata/compile/scoped_principal_policy_set.yaml.golden
  internal/test/testdata/engine/case_13.yaml
  internal/test/testdata/query_planner/policies/principal_policy.yaml
  internal/test/testdata/store/principal_policies/policy_02_acme.yaml
Labels: enhancement

#1012 enhancement: Deduplicate operands to and/or operations
  internal/engine/ast.go
  internal/test/testdata/server/plan_resources/plan_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_00.yaml
Labels: enhancement

#1005 chore(release): Add 0.18.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.18.0.adoc
Labels: chore, release

#1015 docs: Use analogy to explain derived roles
  docs/modules/policies/pages/derived_roles.adoc
Labels: documentation

#1016 docs(backport): Use analogy to explain derived roles (#1015)
  docs/modules/policies/pages/derived_roles.adoc
Labels: documentation

#1013 enhancement: Validate schemas when planning queries
  api/genpb/cerbos/audit/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.validate.go
  api/genpb/cerbos/engine/v1/engine_vtproto.pb.go
  api/genpb/cerbos/engine/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/private/cerbos/private/v1/test.proto
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/response/v1/response.proto
  internal/engine/evaluator.go
  internal/engine/planner.go
  internal/schema/error.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/svc/cerbos_svc.go
  internal/test/testdata/schema/test_cases/check_input_00.yaml
  internal/test/testdata/schema/test_cases/check_input_01.yaml
  internal/test/testdata/schema/test_cases/check_input_02.yaml
  internal/test/testdata/schema/test_cases/check_input_03.yaml
  internal/test/testdata/schema/test_cases/check_input_04.yaml
  internal/test/testdata/schema/test_cases/check_input_05.yaml
  internal/test/testdata/schema/test_cases/check_input_06.yaml
  internal/test/testdata/schema/test_cases/check_input_07.yaml
  internal/test/testdata/schema/test_cases/check_input_08.yaml
  internal/test/testdata/schema/test_cases/plan_resources_input_00.yaml
  internal/test/testdata/schema/test_cases/plan_resources_input_01.yaml
  internal/test/testdata/schema/test_cases/plan_resources_input_02.yaml
  internal/test/testdata/server/plan_resources/plan_case_01.yaml
  internal/test/testdata/server/plan_resources/plan_case_01_acme.hr.uk.yaml
  internal/test/testdata/server/plan_resources/plan_case_01_acme.hr.yaml
  internal/test/testdata/server/plan_resources/plan_case_02_acme.hr.yaml
  internal/test/testdata/server/plan_resources/plan_case_03.yaml
  internal/test/testdata/server/plan_resources/plan_case_05.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_03.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_05.yaml
  schema/jsonschema/cerbos/audit/v1/DecisionLogEntry.schema.json
  schema/jsonschema/cerbos/audit/v1/DecisionLogEntry/PlanResources.schema.json
  schema/jsonschema/cerbos/engine/v1/PlanResourcesOutput.schema.json
  schema/jsonschema/cerbos/response/v1/ListAuditLogEntriesResponse.schema.json
  schema/jsonschema/cerbos/response/v1/PlanResourcesResponse.schema.json
  schema/jsonschema/cerbos/response/v1/PlaygroundProxyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#1020 chore(docs): Fix confdocs panic when no struct tag is provided
  hack/tools/confdocs/confdocs.go
Labels: chore

#1019 chore(ci): Split tests across multiple runners
  .github/dependabot.yml
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/test-matrix.yaml
  .gitignore
  Makefile
  hack/tools/testsplit/buckets.go
  hack/tools/testsplit/combine.go
  hack/tools/testsplit/go.mod
  hack/tools/testsplit/go.sum
  hack/tools/testsplit/main.go
  hack/tools/testsplit/split.go
  hack/tools/testsplit/times.go
  tools/tools.mk
Labels: ci, chore

#1038 enhancement: Output detailed index build errors when the number of errors is low
  cmd/cerbos/compile/compile.go
  internal/storage/index/builder.go
  internal/storage/index/index.go
Labels: enhancement

#1045 chore(test): Fix flaky update store test
  internal/storage/git/store_test.go
Labels: testing, chore

#1046 chore: Add function to compile a set of files
  api/genpb/cerbos/bundle/v1/bundle.pb.go
  api/genpb/cerbos/bundle/v1/bundle.pb.validate.go
  api/genpb/cerbos/bundle/v1/bundle_hashpb.pb.go
  api/genpb/cerbos/bundle/v1/bundle_vtproto.pb.go
  api/genpb/cerbos/bundle/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/genpb/cerbos/runtime/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/runtime/v1/runtime.pb.go
  api/genpb/cerbos/runtime/v1/runtime.pb.validate.go
  api/genpb/cerbos/runtime/v1/runtime_hashpb.pb.go
  api/genpb/cerbos/runtime/v1/runtime_vtproto.pb.go
  api/private/cerbos/bundle/v1/bundle.proto
  api/private/cerbos/private/v1/test.proto
  api/private/cerbos/runtime/v1/runtime.proto
  cmd/cerbos/compile/compile.go
  cmd/cerbos/compile/internal/compilation/display.go
  cmd/cerbos/compile/internal/lint/display.go
  internal/compile/compile.go
  internal/compile/compile_test.go
  internal/compile/context.go
  internal/compile/errors.go
  internal/storage/index/builder.go
  internal/storage/index/builder_test.go
  internal/svc/playground_svc.go
  internal/test/testdata/index/corrupt_files.yaml
  internal/test/testdata/index/disabled_ancestor.yaml
  internal/test/testdata/index/duplicate_definitions.yaml
  internal/test/testdata/index/duplicate_rule_and_role_names.yaml
  internal/test/testdata/index/duplicate_scoped_policies.yaml
  internal/test/testdata/index/incomplete_files.yaml
  internal/test/testdata/index/missing_import.yaml
  internal/test/testdata/index/missing_scopes.yaml
  internal/test/testdata/index/multiple_policies_per_file.yaml
  private/compile/compile.go
  schema/openapiv2/cerbos/bundle/v1/bundle.swagger.json
Labels: chore

#1056 fix: Avoid short-circuit when expressions access non-existent attributes
  internal/engine/engine_test.go
  internal/engine/evaluator.go
  internal/engine/evaluator_test.go
  internal/test/testdata/cel_eval/missing_attr_allof.yaml
  internal/test/testdata/cel_eval/missing_attr_anyof.yaml
  internal/test/testdata/cel_eval/missing_attr_noneof.yaml
  internal/test/testdata/server/playground/test/pgt_case_00.yaml
Labels: bug
