Repository cerbos/cerbos, pull requests merged in 2022-12, with the labels that each got.

#1379 docs(backport): Port SQLAlchemy integration guide from blog to docs (#1378)
  docs/modules/recipes/nav.adoc
  docs/modules/recipes/pages/orm/prisma/index.adoc
  docs/modules/recipes/pages/orm/sqlalchemy/index.adoc
Labels: documentation

#1383 docs: Add excludeMetadataKeys and includeMetadataKeys to audit page on docs
  docs/modules/configuration/pages/audit.adoc
Labels: documentation

#1384 docs(backport): Add excludeMetadataKeys and includeMetadataKeys to audit page on docs (#1383)
  docs/modules/configuration/pages/audit.adoc
Labels: documentation

#1385 feat!: Include metadata in decision logs
  api/genpb/cerbos/audit/v1/audit.pb.go
  api/genpb/cerbos/audit/v1/audit.pb.validate.go
  api/genpb/cerbos/audit/v1/audit_vtproto.pb.go
  api/genpb/cerbos/audit/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/public/cerbos/audit/v1/audit.proto
  client/testutil/server.go
  cmd/cerbosctl/audit/audit.go
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  hack/dev/conf.secure.yaml
  internal/audit/conf.go
  internal/audit/interceptor.go
  internal/audit/interceptor_test.go
  internal/audit/metadata.go
  internal/audit/metadata_test.go
  internal/engine/engine.go
  internal/engine/engine_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/verify/verify_test.go
  schema/jsonschema/cerbos/audit/v1/DecisionLogEntry.schema.json
  schema/jsonschema/cerbos/response/v1/ListAuditLogEntriesResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature

#1387 feat: Support for filtering decision logs
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  hack/dev/conf.secure.yaml
  hack/dev/plan.hurl
  hack/scripts/cover.sh
  internal/audit/conf.go
  internal/audit/decision_filter.go
  internal/audit/decision_filter_test.go
  internal/audit/file/log.go
  internal/audit/file/log_test.go
  internal/audit/local/badgerdb.go
  internal/audit/local/badgerdb_test.go
  internal/audit/log.go
  internal/audit/metadata_test.go
  internal/engine/engine_test.go
Labels: feature

#1388 chore(test): Exercise audit log filtering in E2E tests
  e2e/git/helmfile.yaml
  hack/dev/conf.secure.yaml
Labels: testing, chore

#1386 docs: Update Prisma recipe to bring in line with demo repo
  docs/modules/recipes/pages/orm/prisma/index.adoc
Labels: documentation

#1389 docs(backport): Update Prisma recipe to bring in line with demo repo (#1386)
  docs/modules/recipes/pages/orm/prisma/index.adoc
Labels: documentation

#1396 chore(ci): Add CodeQL analyzer
  .github/workflows/codeql.yml
Labels: ci, chore
