Repository cerbos/cerbos, pull requests merged in 2022-03, with the labels that each got.

#683 chore(test): Modify policy generator to use templates
  hack/loadtest/README.md
  hack/loadtest/check.js
  hack/loadtest/docker-compose.yml
  hack/loadtest/generate.go
  hack/loadtest/genres.go
  hack/loadtest/internal/policy.go
  hack/loadtest/loadtest.sh
  hack/loadtest/templates/policies/derived_roles_alpha.yaml.tpl
  hack/loadtest/templates/policies/derived_roles_beta.yaml.tpl
  hack/loadtest/templates/policies/principal_donald_duck.yaml.tpl
  hack/loadtest/templates/policies/resource_leave_request_20210210.yaml.tpl
  hack/loadtest/templates/policies/resource_leave_request_default_acme.yaml.tpl
  hack/loadtest/templates/policies/resource_leave_request_default_acme_hr.yaml.tpl
  hack/loadtest/templates/policies/resource_leave_request_default_acme_hr_uk.yaml.tpl
  hack/loadtest/templates/policies/resource_leave_request_default_noscope.yaml.tpl
  hack/loadtest/templates/requests/crb_req01.json.tpl
  hack/loadtest/templates/requests/crb_req02.json.tpl
  hack/loadtest/templates/requests/crs_req01.json.tpl
  hack/loadtest/templates/requests/crs_req02.json.tpl
  hack/loadtest/templates/schemas/leave_request.json.tpl
  hack/loadtest/templates/schemas/principal.json.tpl
Labels: testing

#676 feat: Introduce `cerbosctl put`
  client/admin.go
  client/model.go
  cmd/cerbosctl/get/internal/schema/print.go
  cmd/cerbosctl/put/internal/errors/put_error.go
  cmd/cerbosctl/put/internal/files/find.go
  cmd/cerbosctl/put/policy.go
  cmd/cerbosctl/put/put.go
  cmd/cerbosctl/put/schema.go
  cmd/cerbosctl/put_test.go
  cmd/cerbosctl/root/root.go
  docs/modules/cli/pages/cerbosctl.adoc
  internal/schema/io.go
  internal/util/filesystem.go
  internal/util/filesystem_test.go
Labels: feature

#686 enhancement: Do not ignore invalid test suites
  cmd/cerbos/compile/compile.go
  internal/test/testdata/verify/invalid_test/did_not_expected_key_test.yaml
  internal/test/testdata/verify/invalid_test/suite_test.yaml
  internal/verify/verify.go
  internal/verify/verify_test.go
Labels: enhancement

#691 chore(test): Add response and wantedResponse check for the load tests
  hack/loadtest/check.js
Labels: chore

#698 chore(test): Add support for load testing with the postgres store
  hack/loadtest/README.md
  hack/loadtest/check.js
  hack/loadtest/loadtest.sh
Labels: chore

#692 feat: Add healthcheck command
  Dockerfile
  cmd/cerbos/healthcheck/healthcheck.go
  cmd/cerbos/healthcheck/healthcheck_test.go
  cmd/cerbos/main.go
  cmd/cerbos/server/server.go
  docs/modules/cli/pages/cerbos.adoc
Labels: feature

#699 docs: Add context to policy documentation
  docs/modules/policies/pages/derived_roles.adoc
  docs/modules/policies/pages/principal_policies.adoc
  docs/modules/policies/pages/resource_policies.adoc
Labels: documentation

#700 enhancement: Allow compile and schema cache sizes to be configured
  client/testutil/server.go
  cmd/cerbos/compile/compile.go
  docs/modules/configuration/partials/fullconfiguration.adoc
  hack/loadtest/check.js
  hack/loadtest/loadtest.sh
  internal/compile/compile_test.go
  internal/compile/conf.go
  internal/compile/manager.go
  internal/compile/manager_test.go
  internal/engine/engine_test.go
  internal/schema/conf.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/svc/playground_svc.go
  internal/verify/verify_test.go
Labels: enhancement

#701 feat!: Add matrix tests
  api/genpb/cerbos/policy/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_hashpb.pb.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_hashpb.pb.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/private/cerbos/private/v1/test.proto
  api/public/cerbos/policy/v1/policy.proto
  docs/modules/policies/pages/compile.adoc
  internal/test/testdata/verify/invalid_fixture/suite_test.yaml
  internal/test/testdata/verify/test_fixture_get_tests/error_expectation_not_in_input.yaml
  internal/test/testdata/verify/test_fixture_get_tests/error_nonexistent_aux_data.yaml
  internal/test/testdata/verify/test_fixture_get_tests/error_nonexistent_principal.yaml
  internal/test/testdata/verify/test_fixture_get_tests/error_nonexistent_resource.yaml
  internal/test/testdata/verify/test_fixture_get_tests/error_repeated_expectation.yaml
  internal/test/testdata/verify/test_fixture_get_tests/with_aux_data.yaml
  internal/test/testdata/verify/test_fixture_get_tests/without_aux_data.yaml
  internal/test/testdata/verify/valid/inline_fixture_test.yaml
  internal/test/testdata/verify/valid/suite_test.yaml
  internal/test/testdata/verify/valid/udf_test.yaml
  internal/verify/test_fixture.go
  internal/verify/test_fixture_test.go
  internal/verify/test_matrix.go
  internal/verify/verify.go
  internal/verify/verify_test.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature

#706 enhancement: Add cache metrics
  hack/loadtest/conf/cerbos/disk.yml
  hack/loadtest/conf/grafana/dashboards/cerbos.json
  internal/compile/manager.go
  internal/observability/metrics/metrics.go
  internal/schema/schema.go
Labels: enhancement

#721 docs: Update photo-share tutorial tests
  docs/modules/tutorials/examples/photo-share/tests/album_object_test.yaml
  docs/modules/tutorials/pages/photo-share/index.adoc
Labels: documentation

#722 chore(release): Add 0.14.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.14.0.adoc
  docs/modules/releases/pages/v0.14.0/upgrade.adoc
Labels: chore, release

#728 chore: Tweaks to load test scripts
  hack/loadtest/README.md
  hack/loadtest/check.js
  hack/loadtest/conf/cerbos/config.yml
  hack/loadtest/conf/cerbos/disk.yml
  hack/loadtest/conf/cerbos/postgres.yml
  hack/loadtest/docker-compose.yml
  hack/loadtest/ghz/crb_req01.json
  hack/loadtest/ghz/crs_req01.json
  hack/loadtest/ghz/run.sh
  hack/loadtest/loadtest.sh
  hack/loadtest/templates/requests/crb_req01.json.tpl
  hack/loadtest/templates/schemas/leave_request.json.tpl
  hack/loadtest/templates/schemas/principal.json.tpl
  internal/engine/engine.go
Labels: chore

#745 chore(ci): Upgrade to Go 1.18 on CI
  .github/workflows/dependabot.yaml
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/test-matrix.yaml
Labels: ci, chore

#748 chore(ci): Disable telemetry in E2E tests
  e2e/blob/helmfile.yaml
  e2e/git/helmfile.yaml
  e2e/mysql/helmfile.yaml
  e2e/postgres/helmfile.yaml
  e2e/sqlite/helmfile.yaml
  e2e/sqlserver/helmfile.yaml
Labels: ci, chore

#750 chore: Increase playground file limit
  api/genpb/cerbos/request/v1/request.pb.go
  api/public/cerbos/request/v1/request.proto
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: chore

#749 enhancement: Add protobufs for engine traces and test results
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.validate.go
  api/genpb/cerbos/engine/v1/engine_hashpb.pb.go
  api/genpb/cerbos/engine/v1/engine_vtproto.pb.go
  api/genpb/cerbos/engine/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_hashpb.pb.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/policy/v1/policy.proto
  cmd/cerbos/compile/compile.go
  cmd/cerbos/compile/internal/colored/colored.go
  cmd/cerbos/compile/internal/compilation/display.go
  cmd/cerbos/compile/internal/lint/display.go
  cmd/cerbos/compile/internal/printer/printer.go
  cmd/cerbos/compile/internal/verification/display.go
  cmd/cerbos/compile/internal/verification/internal/traces/map.go
  internal/engine/engine.go
  internal/engine/engine_test.go
  internal/engine/evaluator.go
  internal/engine/trace.go
  internal/engine/tracer/context.go
  internal/engine/tracer/sink.go
  internal/printer/colored/colored.go
  internal/printer/printer.go
  internal/test/testdata/verify/valid/empty_test.yaml
  internal/verify/test_fixture.go
  internal/verify/verify.go
  internal/verify/verify_test.go
  schema/jsonschema/cerbos/engine/v1/Trace.schema.json
  schema/jsonschema/cerbos/policy/v1/TestResults.schema.json
  schema/openapiv2/cerbos/audit/v1/audit.swagger.json
  schema/openapiv2/cerbos/engine/v1/engine.swagger.json
  schema/openapiv2/cerbos/policy/v1/policy.swagger.json
  schema/openapiv2/cerbos/request/v1/request.swagger.json
  schema/openapiv2/cerbos/response/v1/response.swagger.json
  schema/openapiv2/cerbos/runtime/v1/runtime.swagger.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#747 enhancement!: Make the test server fully configurable
  .github/workflows/pr-test.yaml
  client/admin_test.go
  client/client.go
  client/client_test.go
  client/model.go
  client/testutil/example_test.go
  client/testutil/server.go
  client/testutil/server_test.go
  cmd/cerbos/compile/compile.go
  cmd/cerbosctl/get/get_test.go
  cmd/cerbosctl/put_test.go
  go.mod
  go.sum
  internal/audit/local/badgerdb.go
  internal/audit/log.go
  internal/compile/compile_test.go
  internal/compile/manager.go
  internal/compile/manager_test.go
  internal/config/config.go
  internal/engine/conf.go
  internal/engine/engine.go
  internal/engine/engine_test.go
  internal/schema/schema.go
  internal/schema/schema_test.go
  internal/server/server_test.go
  internal/storage/blob/store.go
  internal/storage/db/mysql/mysql.go
  internal/storage/db/postgres/postgres.go
  internal/storage/db/sqlite3/sqlite3.go
  internal/storage/db/sqlserver/sqlserver.go
  internal/storage/disk/disk.go
  internal/storage/git/store.go
  internal/storage/store.go
  internal/svc/playground_svc.go
  internal/verify/verify_test.go
  tools/go.mod
  tools/go.sum
Labels: enhancement, sdk

#767 chore(fix): Restrict set of JSON schema enums to match validation rule
  hack/tools/protoc-gen-jsonschema/module/enum.go
  hack/tools/protoc-gen-jsonschema/module/module.go
  schema/jsonschema/cerbos/policy/v1/Policy.schema.json
  schema/jsonschema/cerbos/policy/v1/PrincipalPolicy.schema.json
  schema/jsonschema/cerbos/policy/v1/PrincipalRule.schema.json
  schema/jsonschema/cerbos/policy/v1/ResourcePolicy.schema.json
  schema/jsonschema/cerbos/policy/v1/ResourceRule.schema.json
  schema/jsonschema/cerbos/private/v1/CodeGenTestCase.schema.json
  schema/jsonschema/cerbos/private/v1/CompileTestCase.schema.json
  schema/jsonschema/cerbos/private/v1/ServerTestCase.schema.json
  schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
  schema/jsonschema/cerbos/request/v1/ListAuditLogEntriesRequest.schema.json
  schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
  tools/tools.mk
Labels: chore

#771 enhancement: Improve HTTP health check
  internal/server/server.go
Labels: enhancement

#772 chore: Make playground file limit consistent
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/public/cerbos/request/v1/request.proto
  schema/jsonschema/cerbos/private/v1/ServerTestCase.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundValidateRequest.schema.json
Labels: chore

#777 chore(ci): Only report newly-introduced backwards-compatibility breakage
  .github/workflows/pr-test.yaml
Labels: ci

#779 chore(ci): Delete JSON schemas from latest when removed in a release
  .github/workflows/release.yaml
Labels: ci

#797 chore(ci): Add buf format
  .github/workflows/pr-test.yaml
  Makefile
  api/genpb/cerbos/audit/v1/audit.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/private/cerbos/private/v1/test.proto
  api/private/cerbos/runtime/v1/runtime.proto
  api/private/cerbos/state/v1/state.proto
  api/public/cerbos/audit/v1/audit.proto
  api/public/cerbos/effect/v1/effect.proto
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/policy/v1/policy.proto
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/schema/v1/schema.proto
  api/public/cerbos/svc/v1/svc.proto
  api/public/cerbos/telemetry/v1/telemetry.proto
Labels: ci, chore

#769 feat: Add immediate reloading from the store with Admin API
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_hashpb.pb.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  client/admin.go
  cmd/cerbosctl/root/root.go
  cmd/cerbosctl/store/reload.go
  cmd/cerbosctl/store/store.go
  docs/modules/api/pages/admin_api.adoc
  docs/modules/cli/pages/cerbosctl.adoc
  docs/modules/configuration/pages/storage.adoc
  internal/storage/blob/store.go
  internal/storage/blob/store_test.go
  internal/storage/blob/tests.go
  internal/storage/conf.go
  internal/storage/disk/disk.go
  internal/storage/disk/disk_test.go
  internal/storage/git/store.go
  internal/storage/git/store_test.go
  internal/storage/index/builder.go
  internal/storage/index/index.go
  internal/storage/internal/tests.go
  internal/storage/reload.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/test/mocks/Index.go
  schema/jsonschema/cerbos/request/v1/ReloadStoreRequest.schema.json
  schema/jsonschema/cerbos/response/v1/ReloadStoreResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature

#799 feat: REPL for conditions
  cmd/cerbos/main.go
  cmd/cerbos/repl/internal/banner.txt
  cmd/cerbos/repl/internal/cel.go
  cmd/cerbos/repl/internal/directive.go
  cmd/cerbos/repl/internal/directive_test.go
  cmd/cerbos/repl/internal/help.txt
  cmd/cerbos/repl/internal/repl.go
  cmd/cerbos/repl/internal/repl_test.go
  cmd/cerbos/repl/repl.go
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/policies/pages/conditions.adoc
  go.mod
  go.sum
  internal/conditions/cel.go
  internal/outputcolor/level.go
  internal/printer/colored/colored.go
  tools/go.mod
  tools/go.sum
Labels: feature

#800 docs: Add editor configuration docs
  docs/modules/ROOT/partials/attributes.adoc
  docs/modules/policies/nav.adoc
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/index.adoc
Labels: documentation

#801 docs: Add JetBrains and VSCode authoring tips
  docs/modules/policies/images/jetbrains-menu.png
  docs/modules/policies/pages/authoring_tips.adoc
Labels: documentation

#802 chore: Set minimum Go version to 1.18
  .github/ISSUE_TEMPLATE/bug.yaml
  .golangci.yaml
  CONTRIBUTING.md
  Makefile
  go.mod
  hack/tools/protoc-gen-jsonschema/go.mod
  tools/go.mod
Labels: chore

#803 fix: Handle comments at the beginning of YAML files
  internal/test/testdata/policy_formats/derived_roles_01.yaml
  internal/test/testdata/policy_formats/principal_policy_01.yaml
  internal/test/testdata/policy_formats/resource_policy_01.yaml
  internal/util/serdeio.go
Labels: bug
