Repository cerbos/cerbos, pull requests merged in 2022-10, with the labels that each got.

#1262 fix: Validate required fields in `PlanResourcesRequest`
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/public/cerbos/request/v1/request.proto
  schema/jsonschema/cerbos/request/v1/PlanResourcesRequest.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundProxyRequest.schema.json
Labels: bug

#1265 docs(backport): Added `Engineering` section with post on single process usage (#1264)
  docs/antora.yml
  docs/modules/engineering/assets/images/organisation.png
  docs/modules/engineering/nav.adoc
  docs/modules/engineering/pages/index.adoc
  docs/modules/engineering/pages/why_cerbos_runs_as_a_separate_process.adoc
Labels: documentation

#1275 chore(ci): Use latest Go version in builds
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/vulnerability-check.yaml
Labels: ci, chore

#1274 docs: README key concepts
  README.md
Labels: documentation

#1277 chore(ci): Set output via environment file rather than stdout
  .github/workflows/pr-test.yaml
Labels: ci, chore

#1278 fix: Update hasIntersection function to support partial eval
  internal/conditions/cerbos_lib.go
  internal/engine/ast.go
  internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map.yaml
Labels: bug

#1282 chore: Confirm hierarchy funcs support partial eval
  internal/test/testdata/query_planner/policies/resource_policy_hierarchy.yaml
  internal/test/testdata/query_planner/suite/hierarchy_user.yaml
  internal/test/testdata/query_planner/suite/maggie.yaml
Labels: chore

#1281 feat: Update list functions to support partial eval
  internal/conditions/cerbos_lib.go
  internal/engine/planner_test.go
  internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map.yaml
Labels: feature

#1307 chore: Stable string representation for query filter
  go.mod
  internal/engine/ast.go
Labels: chore

#1301 fix: Derived role condition is optional
  internal/engine/planner.go
  internal/test/testdata/query_planner/policies/resource_policy_leave_request.yaml
  internal/test/testdata/query_planner/suite/harry.yaml
Labels: bug

#1313 docs: Updating the logos
  README.md
Labels: documentation

#1316 chore(ci): Remove single commit validation
  .github/workflows/pr-title.yaml
Labels: ci, chore

#1317 fix: Handling of null value by the query planner
  internal/engine/ast.go
  internal/test/testdata/query_planner/policies/resource_policy_contact.yaml
  internal/test/testdata/query_planner/suite/donald_duck.yaml
Labels: bug

#1321 docs: Updated the user logos on the readme
  README.md
Labels: documentation

#1324 chore: Re-generate mocks
  internal/test/mocks/Index.go
  internal/test/mocks/Store.go
Labels: chore
