Repository cerbos/cerbos, pull requests merged in 2022-07, with the labels that each got.

#1057 chore(release): Add 0.19.0 release notes
  docs/modules/configuration/pages/tracing.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.19.0.adoc
Labels: chore, release

#1082 chore: Add metadata field to bundle manifest
  api/genpb/cerbos/bundle/v1/bundle.pb.go
  api/genpb/cerbos/bundle/v1/bundle.pb.validate.go
  api/genpb/cerbos/bundle/v1/bundle_hashpb.pb.go
  api/genpb/cerbos/bundle/v1/bundle_vtproto.pb.go
  api/genpb/cerbos/bundle/v1/hashpb_helpers.pb.go
  api/private/cerbos/bundle/v1/bundle.proto
Labels: chore

#1083 chore(refactor): Replace deprecated CEL options
  go.mod
  go.sum
  internal/conditions/cerbos_lib.go
  internal/conditions/types/hierarchy.go
Labels: chore, refactoring

#1091 chore(ci): Use pull request title to apply labels
  .github/workflows/pr-title.yaml
  hack/scripts/apply-pr-labels.sh
Labels: ci, chore

#1092 docs: Add links to PHP SDK
  README.md
  docs/modules/api/assets/images/nodejs.svg
  docs/modules/api/assets/images/php.svg
  docs/modules/api/pages/index.adoc
Labels: documentation

#1093 docs(backport): Add links to PHP SDK (#1092)
  README.md
  docs/modules/api/assets/images/nodejs.svg
  docs/modules/api/assets/images/php.svg
  docs/modules/api/pages/index.adoc
Labels: documentation

#1107 chore: Add function to run policy tests
  private/verify/verify.go
  private/verify/verify_test.go
Labels: chore
