Repository cerbos/cerbos, pull requests merged in 2022-01, with the labels that each got.

#537 enhancement: Strict JSON request parsing
  internal/server/server.go
Labels: enhancement

#541 chore(test): Tests for AddOrUpdateSchema endpoint
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/private/cerbos/private/v1/test.proto
  internal/schema/schema_test.go
  internal/server/server_test.go
  internal/storage/db/internal/db.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  internal/test/test.go
  internal/test/testdata/server/admin/add_or_update_schema/case_00.yaml
  internal/test/testdata/server/admin/add_or_update_schema/invalid_case_00.yaml
Labels: testing, chore

#544 chore(test): Add end-to-end test suite
  Makefile
  api/private/buf.lock
  api/public/buf.lock
  e2e/README.md
  e2e/blob/blob_test.go
  e2e/blob/helmfile.yaml
  e2e/cleanup.sh
  e2e/git/git_test.go
  e2e/git/helmfile.yaml
  e2e/mysql/helmfile.yaml
  e2e/mysql/mysql_test.go
  e2e/postgres/helmfile.yaml
  e2e/postgres/postgres_test.go
  e2e/run.sh
  e2e/sqlite/helmfile.yaml
  e2e/sqlite/sqlite_test.go
  go.mod
  go.sum
  hack/dev/admin.hurl
  hack/dev/check.hurl
  hack/dev/dev.mk
  hack/dev/plan.hurl
  hack/dev/playground.hurl
  hack/dev/requests/admin_add_or_update_policy/req01.json
  internal/server/server_test.go
  internal/server/tests.go
  internal/storage/blob/cloner_test.go
  internal/storage/blob/store_test.go
  internal/storage/blob/tests.go
  internal/storage/db/mysql/schema.sql
  internal/storage/index/builder.go
  internal/test/e2e/ctx.go
  internal/test/e2e/setup.go
  internal/test/e2e/tests.go
  internal/test/e2e/util.go
  tools/go.mod
  tools/go.sum
Labels: testing, chore, tooling

#553 chore(bug): Handle case when query plan filter is nil
  internal/engine/ast.go
  internal/test/testdata/query_planner/policies/resource_policy.yaml
  internal/test/testdata/query_planner/suite/adam.yaml
Labels: bug, chore

#554 chore(ci): Add workflow to run E2E tests
  .github/workflows/e2e.yaml
  e2e/README.md
  e2e/kind.yaml
  e2e/run.sh
Labels: ci, chore

#556 chore(ci): Run E2E tests on schedule
  .github/workflows/e2e.yaml
  e2e/blob/blob_test.go
  e2e/git/git_test.go
  e2e/mysql/mysql_test.go
  e2e/postgres/postgres_test.go
  e2e/run.sh
  e2e/sqlite/sqlite_test.go
  internal/server/server_test.go
  internal/server/tests.go
  internal/test/e2e/tests.go
Labels: ci, chore

#557 chore(ci): Enable server tests in CI
  internal/server/server_test.go
Labels: ci, chore

#559 docs: Document the query plan response
  docs/modules/api/pages/index.adoc
Labels: documentation

#536 feat!: Replace `cerbosctl list` with `cerbosctl get`
  client/admin.go
  client/model.go
  cmd/cerbosctl/cerbosctl_test.go
  cmd/cerbosctl/get/derivedroles/derived_roles.go
  cmd/cerbosctl/get/get.go
  cmd/cerbosctl/get/internal/flagset/filter.go
  cmd/cerbosctl/get/internal/flagset/format.go
  cmd/cerbosctl/get/internal/policy/policy.go
  cmd/cerbosctl/get/internal/policy/prerun.go
  cmd/cerbosctl/get/internal/printer/tablewriter.go
  cmd/cerbosctl/get/internal/schema/schema.go
  cmd/cerbosctl/get/principalpolicy/principal_policy.go
  cmd/cerbosctl/get/resourcepolicy/resource_policy.go
  cmd/cerbosctl/get/schema/schema.go
  cmd/cerbosctl/internal/definitions.go
  cmd/cerbosctl/internal/flags.go
  cmd/cerbosctl/internal/print.go
  cmd/cerbosctl/list/list.go
  cmd/cerbosctl/main.go
  docs/modules/cli/pages/ctl.adoc
  go.mod
  go.sum
  internal/test/policy.go
Labels: enhancement

#563 chore(ci): Add CodeCov integration
  .github/codecov.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/snaphot.yaml
  .gitignore
  Makefile
Labels: ci, chore

#562 feat: Enable switching off schema validation for certain actions
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/public/cerbos/policy/v1/policy.proto
  docs/modules/policies/pages/schemas.adoc
  internal/engine/cache.go
  internal/engine/evaluator.go
  internal/engine/planner.go
  internal/schema/schema.go
  internal/test/testdata/schema/test_cases/case_06.yaml
  internal/test/testdata/schema/test_cases/case_07.yaml
  internal/test/testdata/schema/test_cases/case_08.yaml
  internal/util/globs.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature

#573 chore(release): Add 0.12.0 release notes
  docs/modules/api/pages/admin_api.adoc
  docs/modules/api/pages/index.adoc
  docs/modules/cli/pages/ctl.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.12.0.adoc
Labels: chore, release

#588 chore: Fix lint issues
  .golangci.yaml
  Makefile
  client/client_test.go
  cmd/cerbosctl/main.go
  internal/compile/manager.go
  internal/compile/manager_test.go
  internal/conditions/cerbos_lib.go
  internal/engine/ast.go
  internal/server/server.go
  internal/server/tests.go
  tools/go.mod
  tools/go.sum
Labels: chore

#589 docs(backport): Add service model explanation (#587)
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#591 docs: Update CLI docs
  docs/modules/cli/nav.adoc
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/cli/pages/cerbosctl.adoc
  docs/modules/cli/pages/compile.adoc
  docs/modules/cli/pages/index.adoc
  docs/modules/cli/pages/server.adoc
Labels: documentation

#592 docs(backport): Update CLI docs (#591)
  docs/modules/cli/nav.adoc
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/cli/pages/cerbosctl.adoc
  docs/modules/cli/pages/compile.adoc
  docs/modules/cli/pages/index.adoc
  docs/modules/cli/pages/server.adoc
Labels: documentation

#590 chore: Update Antora and Goreleaser config
  .github/actions/antora-docs/action.yaml
  .goreleaser.yml
  Makefile
  docs/build.sh
Labels: chore

#596 chore(test): Add golden files for compile results
  cmd/cerbosctl/cerbosctl_test.go
  cmd/cerbosctl/internal/print.go
  internal/compile/compile_test.go
  internal/test/test.go
  internal/test/testdata/compile/multiple_imports.yaml.golden
  internal/test/testdata/compile/only_derived_roles.yaml
  internal/test/testdata/compile/only_derived_roles.yaml.golden
  internal/test/testdata/compile/principal_policy.yaml.golden
  internal/test/testdata/compile/simple_valid_policy_set.yaml.golden
Labels: testing, chore
