Repository cerbos/cerbos, pull requests merged in 2022-04, with the labels that each got.

#805 chore: Replace CORS handler
  go.mod
  go.sum
  internal/server/middleware.go
  internal/server/tests.go
Labels: chore

#804 chore(release): Add 0.15.0 release notes
  .gitattributes
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/releases/assets/images/repl.gif
  docs/modules/releases/assets/images/schema_edit.gif
  docs/modules/releases/assets/images/test_output.png
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.15.0.adoc
Labels: chore, release

#807 chore: Rename interface{} to any and use Go build info
  client/client_test.go
  client/model.go
  client/testutil/example_test.go
  client/testutil/server.go
  cmd/cerbos/compile/internal/verification/display.go
  cmd/cerbos/repl/internal/repl.go
  cmd/cerbos/repl/internal/repl_test.go
  cmd/cerbos/run/run.go
  cmd/cerbos/server/server.go
  cmd/cerbosctl/get/get_test.go
  cmd/cerbosctl/put_test.go
  hack/tools/confdocs/confdocs.go
  internal/audit/conf.go
  internal/audit/conf_test.go
  internal/audit/context.go
  internal/audit/interceptor.go
  internal/audit/local/badgerdb.go
  internal/auxdata/conf_test.go
  internal/auxdata/jwt_test.go
  internal/compile/context.go
  internal/compile/manager.go
  internal/conditions/cerbos_lib.go
  internal/conditions/cerbos_lib_test.go
  internal/conditions/types/hierarchy.go
  internal/config/config.go
  internal/config/config_test.go
  internal/engine/evaluator.go
  internal/engine/evaluator_test.go
  internal/engine/planner.go
  internal/engine/tracer/context.go
  internal/namer/namer.go
  internal/outputcolor/level.go
  internal/printer/printer.go
  internal/schema/schema.go
  internal/server/codec.go
  internal/server/conf_test.go
  internal/server/middleware.go
  internal/storage/conf.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/funcs.go
  internal/storage/db/internal/funcs_test.go
  internal/storage/db/internal/model.go
  internal/storage/index/index.go
  internal/storage/reload.go
  internal/storage/storage_test.go
  internal/storage/store.go
  internal/svc/helpers.go
  internal/telemetry/telemetry.go
  internal/test/template.go
  internal/util/app.go
  internal/util/hash.go
  internal/util/hash_test.go
  internal/util/pb.go
Labels: chore

#806 chore(ci): Use the same format for GCS buckets
  .github/workflows/release.yaml
Labels: ci, chore

#819 feat: Unified check API
  README.md
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/private/v1/test.pb.validate.go
  api/genpb/cerbos/private/v1/test_hashpb.pb.go
  api/genpb/cerbos/private/v1/test_vtproto.pb.go
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_hashpb.pb.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_hashpb.pb.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/private/cerbos/private/v1/test.proto
  api/public/cerbos/engine/v1/engine.proto
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  client/client.go
  client/client_test.go
  client/example_test.go
  client/model.go
  docs/modules/ROOT/examples/quickstart_request.txt
  docs/modules/ROOT/pages/quickstart.adoc
  docs/modules/api/pages/index.adoc
  docs/modules/tutorials/pages/photo-share/index.adoc
  internal/server/tests.go
  internal/svc/cerbos_svc.go
  internal/test/testdata/server/checks/check_resources/cr_case_00.yaml
  internal/test/testdata/server/checks/check_resources/cr_case_01.yaml
  internal/test/testdata/server/checks/check_resources/cr_case_02.yaml
  internal/test/testdata/server/checks/check_resources/cr_case_03.yaml
  internal/test/testdata/server/checks/check_resources/cr_case_04.yaml
  internal/test/testdata/server/checks/check_resources/cr_case_05.yaml
  internal/test/testdata/server/checks/check_resources/cr_invalid_case_00.yaml
  internal/test/testdata/server/checks/check_resources/cr_invalid_case_01.yaml
  internal/test/testdata/server/checks/check_resources/cr_invalid_case_02.yaml
  schema/jsonschema/cerbos/request/v1/CheckResourcesRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourcesRequest/ResourceEntry.schema.json
  schema/jsonschema/cerbos/response/v1/CheckResourcesResponse.schema.json
  schema/jsonschema/cerbos/response/v1/CheckResourcesResponse/ResultEntry.schema.json
  schema/jsonschema/cerbos/response/v1/CheckResourcesResponse/ResultEntry/Meta.schema.json
  schema/jsonschema/cerbos/response/v1/CheckResourcesResponse/ResultEntry/Meta/EffectMeta.schema.json
  schema/jsonschema/cerbos/response/v1/CheckResourcesResponse/ResultEntry/Resource.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature

#822 docs: Fix ID attribute in testing docs
  docs/modules/policies/pages/compile.adoc
Labels: documentation

#825 chore(release): Add 0.15.1 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.15.1.adoc
Labels: chore, release

#826 chore: Group changelog items
  .goreleaser.yml
Labels: chore

#827 chore(backport): Add 0.15.1 release notes (#825)
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.15.1.adoc
Labels: chore, release

#820 enhancement: Execute policy conditions in the CEL REPL
  cmd/cerbos/repl/internal/cel.go
  cmd/cerbos/repl/internal/directive.go
  cmd/cerbos/repl/internal/eval.go
  cmd/cerbos/repl/internal/help.txt
  cmd/cerbos/repl/internal/repl.go
  cmd/cerbos/repl/internal/repl_test.go
  cmd/cerbos/repl/repl.go
  docs/modules/cli/pages/cerbos.adoc
  internal/printer/colored/colored.go
  internal/printer/printer.go
  internal/test/testdata/store/derived_roles/derived_roles_01.yaml
Labels: enhancement

#821 chore: Add CheckResources API to Playground
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  internal/svc/playground_svc.go
  internal/test/testdata/server/playground/proxy/pgp_cr_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_case_02.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_case_03.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_case_04.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_case_05.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_invalid_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_invalid_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_cr_invalid_case_03.yaml
  schema/jsonschema/cerbos/request/v1/PlaygroundProxyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/PlaygroundProxyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: chore

#853 enhancement: Policy variables in the REPL
  cmd/cerbos/repl/internal/directive_test.go
  cmd/cerbos/repl/internal/repl.go
  cmd/cerbos/repl/internal/repl_test.go
Labels: enhancement

#859 enhancement: Auto-detect end of input in REPL
  cmd/cerbos/repl/internal/repl.go
  cmd/cerbos/repl/internal/repl_test.go
  cmd/cerbos/repl/internal/stack.go
Labels: enhancement

#871 docs: Document Jaeger trace format
  docs/modules/configuration/pages/tracing.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/observability/tracing/conf.go
Labels: documentation

#876 chore(release): Add 0.16.0 release notes
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.16.0.adoc
Labels: chore, release

#877 docs: Add links to new SDKs
  docs/modules/api/pages/index.adoc
Labels: documentation
