Repository cerbos/cerbos, pull requests merged in 2022-11, with the labels that each got.

#1327 feat: Optimise query plan for index into struct
  internal/engine/engine.go
  internal/engine/evaluator.go
  internal/engine/evaluator_test.go
  internal/engine/internal/utils.go
  internal/engine/internal/utils_test.go
  internal/engine/planner/ast.go
  internal/engine/planner/ast_test.go
  internal/engine/planner/internal/utils.go
  internal/engine/planner/lambda.go
  internal/engine/planner/matchers/struct_matcher.go
  internal/engine/planner/matchers/struct_matcher_test.go
  internal/engine/planner/planner.go
  internal/engine/planner/planner_test.go
  internal/engine/planner/testdata/ast_build_expr.yaml
  internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map.yaml
Labels: feature

#1325 fix(sdk): Missing setters in policy builders
  client/model.go
  client/model_test.go
Labels: bug

#1329 docs: Fix formatting of table in tutorial
  docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc
Labels: documentation

#1331 docs(backport): Fix formatting of table in tutorial
  docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc
Labels: documentation

#1332 docs: Add tip about using cerbosctl to load policies
  docs/modules/configuration/pages/storage.adoc
  docs/modules/configuration/partials/cerbosctl.adoc
Labels: documentation

#1336 fix: Disable CGO for "compile" and "test" make targets
  Makefile
Labels: bug

#1335 chore(release): Add 0.22.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.22.0.adoc
Labels: chore, release

#1338 docs: Add recipe link to admin API demo
  docs/modules/recipes/nav.adoc
Labels: documentation

#1339 docs(backport): Add recipe link to admin API demo (#1338)
  docs/modules/recipes/nav.adoc
Labels: documentation

#1341 chore: Disable CGO for "all" make target
  Makefile
Labels: chore

#1342 enhancement: Clearer errors when trying to query audit logs
  internal/audit/conf_test.go
  internal/audit/file/log.go
  internal/audit/file/log_test.go
  internal/audit/local/badgerdb.go
  internal/audit/local/badgerdb_test.go
  internal/audit/log.go
  internal/svc/admin_svc.go
Labels: enhancement

#1344 docs: Add link to git-sync
  docs/modules/configuration/pages/storage.adoc
Labels: documentation

#1345 docs(backport): Add link to git-sync (#1344)
  docs/modules/configuration/pages/storage.adoc
Labels: documentation

#1347 fix(sdk): Set scope of the plan resources request
  client/client.go
Labels: bug

#1343 enhancement: Support zip files in cerbosctl put
  .gitattributes
  .github/workflows/pr-test.yaml
  cmd/cerbosctl/put/internal/files/find.go
  cmd/cerbosctl/put/internal/files/found.go
  cmd/cerbosctl/put/policy.go
  cmd/cerbosctl/put/schema.go
  cmd/cerbosctl/put_test.go
  cmd/cerbosctl/testdata/store.zip
  docs/modules/cli/pages/cerbosctl.adoc
  internal/util/filesystem.go
Labels: enhancement

#1350 fix: Rewrite log level change without Go 1.19 features
  go.mod
  internal/observability/logging/logging.go
Labels: bug

#1352 chore(ci): Enable LFS for snapshot build
  .github/workflows/snaphot.yaml
Labels: ci, chore

#1351 fix(planner): Known resource attribute as an index into a struct
  internal/conditions/cerbos_lib.go
  internal/engine/planner/ast.go
  internal/engine/planner/internal/utils.go
  internal/engine/planner/matchers/struct_matcher.go
  internal/engine/planner/planner.go
  internal/engine/planner/planner_test.go
  internal/test/testdata/query_planner/policies/derived_roles/workspace.yaml
  internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map_admin.yaml
Labels: bug

#1353 enhancement(planner): Optimize membership test expression having index into struct
  internal/engine/planner/matchers/struct_matcher.go
  internal/engine/planner/matchers/struct_matcher_test.go
  internal/engine/planner/planner.go
  internal/test/testdata/query_planner/suite/report_with_map.yaml
  internal/test/testdata/query_planner/suite/report_with_map_admin.yaml
Labels: enhancement

#1355 chore(release): Add 0.22.1 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.22.1.adoc
Labels: chore, release

#1358 chore(release): Add 0.23.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.23.0.adoc
Labels: chore, release

#1359 chore(ci): Disable Renovate go.mod Go version update
  .github/renovate.json
Labels: ci, chore

#1363 enhancement(helm): Annotations for deployment and service
  deploy/charts/cerbos/templates/_helpers.tpl
  deploy/charts/cerbos/templates/deployment.yaml
  deploy/charts/cerbos/templates/service.yaml
  deploy/charts/cerbos/values-jaeger-agent.yaml
  deploy/charts/cerbos/values.yaml
Labels: enhancement

#1364 fix: Flaky query plan test
  internal/engine/planner/matchers/struct_matcher.go
Labels: bug

#1368 docs: Remove unstable warning from Linux packages
  docs/modules/ROOT/pages/installation/binary.adoc
Labels: documentation

#1366 docs: List available SDKs
  docs/modules/ROOT/pages/tutorial/09_integrating-cerbos.adoc
Labels: documentation

#1369 docs(backport): Remove unstable warning from Linux packages (#1368)
  docs/modules/ROOT/pages/installation/binary.adoc
Labels: documentation

#1371 fix(planner): R.id unresolved
  internal/engine/planner/planner.go
  internal/test/testdata/query_planner/policies/resource_policy_basics.yaml
  internal/test/testdata/query_planner/suite/basics.yaml
Labels: bug

#1374 fix(planner): R.id unresolved (#1371)
  internal/engine/planner/planner.go
  internal/test/testdata/query_planner/policies/resource_policy_basics.yaml
  internal/test/testdata/query_planner/suite/basics.yaml
Labels: bug

#1372 enhancement(helm): Annotations for deployment and service (#1363)
  deploy/charts/cerbos/templates/_helpers.tpl
  deploy/charts/cerbos/templates/deployment.yaml
  deploy/charts/cerbos/templates/service.yaml
  deploy/charts/cerbos/values-jaeger-agent.yaml
  deploy/charts/cerbos/values.yaml
Labels: enhancement

#1375 chore(release): Add 0.23.1 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.23.1.adoc
Labels: chore, release

#1376 chore(release): Prepare v0.23.1 release
  deploy/charts/cerbos/Chart.yaml
  docs/antora-playbook.yml
  docs/antora.yml
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.23.1.adoc
Labels: chore, release

#1361 docs: Add policy best practices section
  docs/modules/ROOT/examples/quickstart/example.java
  docs/modules/policies/examples/curl.txt
  docs/modules/policies/examples/example.cs
  docs/modules/policies/examples/example.go
  docs/modules/policies/examples/example.java
  docs/modules/policies/examples/example.js
  docs/modules/policies/examples/example.php
  docs/modules/policies/examples/example.py
  docs/modules/policies/examples/example.rb
  docs/modules/policies/examples/example.rs
  docs/modules/policies/nav.adoc
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/best_practices.adoc
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#1377 docs(backport): Add policy best practices section (#1361)
  docs/modules/ROOT/examples/quickstart/example.java
  docs/modules/policies/examples/curl.txt
  docs/modules/policies/examples/example.cs
  docs/modules/policies/examples/example.go
  docs/modules/policies/examples/example.java
  docs/modules/policies/examples/example.js
  docs/modules/policies/examples/example.php
  docs/modules/policies/examples/example.py
  docs/modules/policies/examples/example.rb
  docs/modules/policies/examples/example.rs
  docs/modules/policies/nav.adoc
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/best_practices.adoc
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#1378 docs: Port SQLAlchemy integration guide from blog to docs
  docs/modules/recipes/nav.adoc
  docs/modules/recipes/pages/orm/prisma/index.adoc
  docs/modules/recipes/pages/orm/sqlalchemy/index.adoc
Labels: documentation
