Repository cerbos/cerbos, pull requests merged in 2022-08, with the labels that each got.

#1108 chore(perf): Add template for CheckResources request
  hack/loadtest/docker-compose.yml
  hack/loadtest/templates/requests/cr_req01.json.tpl
  hack/loadtest/templates/requests/cr_req02.json.tpl
Labels: chore

#1125 enhancement: Use plan decorator to provide consistent time functions
  internal/conditions/cerbos_lib.go
Labels: enhancement, performance

#1128 chore(ci): Add docs preview
  .github/workflows/pr-test.yaml
Labels: ci, chore

#1129 chore(ci): Deploy docs previews
  .github/workflows/pr-test.yaml
Labels: ci, chore

#1126 docs: Tabs-block multi language quickstart examples
  docs/antora-playbook.yml
  docs/modules/ROOT/examples/quickstart/curl.txt
  docs/modules/ROOT/examples/quickstart/example.go
  docs/modules/ROOT/examples/quickstart/example.js
  docs/modules/ROOT/examples/quickstart/example.php
  docs/modules/ROOT/examples/quickstart/example.py
  docs/modules/ROOT/examples/quickstart/example.rb
  docs/modules/ROOT/examples/quickstart/example.rs
  docs/modules/ROOT/pages/quickstart.adoc
  docs/supplemental-ui/css/tabs-block.css
  docs/supplemental-ui/partials/footer-content.hbs
  docs/supplemental-ui/partials/head-meta.hbs
  docs/supplemental-ui/tabs-block/behaviour.js
  docs/supplemental-ui/tabs-block/extension.js
Labels: documentation

#1127 chore(ci): Use Go 1.19 in CI
  .github/workflows/dependabot.yaml
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/test-matrix.yaml
  .golangci.yaml
  api/genpb/cerbos/audit/v1/audit.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/private/v1/test.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/runtime/v1/runtime.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry.pb.go
  internal/audit/id.go
  internal/engine/ast.go
  internal/namer/namer.go
  internal/storage/blob/conf.go
  internal/storage/conf.go
  internal/storage/db/internal/tests.go
  internal/storage/db/mysql/conf.go
  internal/storage/db/postgres/conf.go
  internal/storage/db/sqlite3/conf.go
  internal/storage/db/sqlserver/conf.go
  internal/storage/disk/conf.go
  internal/storage/disk/disk_test.go
  internal/storage/git/conf.go
  internal/storage/git/store_test.go
  internal/svc/admin_svc.go
  internal/test/test.go
Labels: ci, chore

#1133 chore(ci): Update Netlify conf
  netlify.toml
Labels: ci, chore

#1149 chore(deps): Use latest otel semconv version
  internal/observability/tracing/tracing.go
Labels: chore

#1150 chore(test): Update E2E setup script
  .github/workflows/e2e.yaml
  e2e/run.sh
Labels: testing, chore

#1151 fix(sdk): Allow setting scope on SDK requests
  client/client_test.go
  client/model.go
Labels: bug

#1152 fix(backport): Allow setting scope on SDK requests
  client/client_test.go
  client/model.go
Labels: bug

#1153 chore(release): Add 0.19.1 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.19.1.adoc
Labels: chore, release

#1154 chore(release): Prepare release 0.19.1
  deploy/charts/cerbos/Chart.yaml
  docs/antora-playbook.yml
  docs/antora.yml
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.19.1.adoc
Labels: chore, release

#1157 docs: Fix broken links to tutorial files
  docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc
  docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc
  docs/modules/ROOT/pages/tutorial/04_testing-policies.adoc
  docs/modules/ROOT/pages/tutorial/05_adding-conditions.adoc
  docs/modules/ROOT/pages/tutorial/06_derived-roles.adoc
  docs/modules/ROOT/pages/tutorial/07_principal-policies.adoc
  docs/modules/ROOT/pages/tutorial/08_attribute-schema.adoc
  docs/modules/ROOT/partials/attributes.adoc
Labels: documentation

#1158 chore(ci): Remove docs preview generation
  .github/workflows/pr-test.yaml
Labels: ci, chore

#1155 chore(ci): Make PR labels job optional
  .github/workflows/pr-title.yaml
Labels: ci, chore

#1166 fix: Allow wildcards for principal policy resource names
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/public/cerbos/policy/v1/policy.proto
  internal/test/testdata/store/principal_policies/policy_01.yaml
  schema/jsonschema/cerbos/policy/v1/Policy.schema.json
  schema/jsonschema/cerbos/policy/v1/PrincipalPolicy.schema.json
  schema/jsonschema/cerbos/policy/v1/PrincipalRule.schema.json
  schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
  schema/jsonschema_test.go
Labels: bug

#1171 enhancement: Warn if (and only if) using the default admin password
  internal/server/conf.go
  internal/server/conf_test.go
  internal/server/server.go
Labels: enhancement

#1172 chore(release): Add 0.20.0 release notes
  docs/modules/policies/pages/compile.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.20.0.adoc
Labels: chore, release

#1179 docs: Add Java and .NET code examples to quickstart
  docs/modules/ROOT/examples/quickstart/example.cs
  docs/modules/ROOT/examples/quickstart/example.java
  docs/modules/ROOT/pages/quickstart.adoc
  docs/supplemental-ui/css/tabs-block.css
Labels: documentation

#1180 docs(backport): Add Java and .NET code examples to quickstart (#1179)
  docs/modules/ROOT/examples/quickstart/example.cs
  docs/modules/ROOT/examples/quickstart/example.java
  docs/modules/ROOT/pages/quickstart.adoc
  docs/supplemental-ui/css/tabs-block.css
Labels: documentation

#1181 chore(deps): Update dependencies
  go.mod
  go.sum
Labels: chore

#1182 chore: Refactor private/verify package
  internal/verify/test_fixture.go
  internal/verify/verify.go
  private/verify/verify.go
Labels: chore
