Repository cerbos/cerbos, pull requests merged in 2022-05, with the labels that each got.

#891 docs: Add MacOS command variant for password generation
  docs/modules/configuration/pages/server.adoc
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#888 docs: Add glossary
  docs/antora.yml
  docs/modules/glossary/nav.adoc
  docs/modules/glossary/pages/index.adoc
Labels: documentation

#889 chore(ci): Update changelog grouping
  .goreleaser.yml
Labels: ci, chore

#905 chore: Update Otel semconv version
  internal/observability/tracing/tracing.go
Labels: chore

#910 fix(ci): Fix confdocs panicking when no comment for a struct provided
  hack/tools/confdocs/confdocs.go
Labels: bug, ci

#912 chore(ci): Update README of the E2E tests to reflect the change of the helmfile repository
  e2e/README.md
Labels: ci, chore

#907 chore(e2e): Add E2E test with tracing enabled
  e2e/jaeger/helmfile.yaml
  e2e/jaeger/jaeger_test.go
Labels: testing, chore

#909 feat: Add file backend for audit logs
  docs/modules/cli/pages/cerbosctl.adoc
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/file/conf.go
  internal/audit/file/log.go
  internal/audit/file/log_test.go
  internal/audit/log.go
  internal/audit/log_test.go
  internal/server/server.go
  internal/svc/admin_svc.go
Labels: feature

#915 docs(backport): Add glossary
  docs/antora.yml
  docs/modules/glossary/nav.adoc
  docs/modules/glossary/pages/index.adoc
Labels: documentation

#914 docs: Add links to demos
  docs/modules/ROOT/pages/quickstart.adoc
  docs/modules/tutorials/nav.adoc
Labels: documentation

#919 docs: Add new SDK links to README and docs
  README.md
  docs/modules/api/pages/index.adoc
Labels: documentation

#918 fix: Return DENY from query plan when no policy or action matches
  internal/engine/engine.go
  internal/engine/planner.go
  internal/test/testdata/query_planner/suite/donald_duck.yaml
  internal/test/testdata/query_planner/suite/harry.yaml
  internal/test/testdata/server/plan_resources/plan_case_03.yaml
  internal/test/testdata/server/plan_resources/plan_case_04.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_04.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_05.yaml
Labels: bug

#930 docs: Document limits on `resources` and `actions`
  docs/modules/api/pages/index.adoc
Labels: documentation

#931 docs(backport): Document limits on `resources` and `actions` (#930)
  docs/modules/api/pages/index.adoc
Labels: documentation

#924 chore: Add API usage stats to telemetry
  api/genpb/cerbos/telemetry/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry.pb.validate.go
  api/genpb/cerbos/telemetry/v1/telemetry_hashpb.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry_vtproto.pb.go
  api/public/cerbos/telemetry/v1/telemetry.proto
  cmd/cerbosctl/put_test.go
  docs/modules/ROOT/pages/telemetry.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/server/server.go
  internal/telemetry/conf.go
  internal/telemetry/middleware.go
  internal/telemetry/middleware_test.go
  internal/telemetry/server_launch.go
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
  schema/jsonschema/cerbos/telemetry/v1/Event.schema.json
  schema/jsonschema/cerbos/telemetry/v1/Event/ApiActivity.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Cerbos.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/AdminApi.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Audit.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Schema.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Storage.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Storage/Blob.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Storage/Disk.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Features/Storage/Git.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Source.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Stats.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Stats/Policy.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerLaunch/Stats/Schema.schema.json
  schema/jsonschema/cerbos/telemetry/v1/ServerStop.schema.json
Labels: chore

#920 enhancement: Allow rule match on any role
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/public/cerbos/policy/v1/policy.proto
  client/client_test.go
  docs/modules/policies/pages/derived_roles.adoc
  docs/modules/policies/pages/resource_policies.adoc
  internal/compile/compile.go
  internal/engine/evaluator.go
  internal/engine/evaluator_test.go
  internal/engine/planner_test.go
  internal/server/tests.go
  internal/storage/blob/cloner_test.go
  internal/storage/index/builder_test.go
  internal/test/testdata/compile/any_role.yaml
  internal/test/testdata/compile/any_role.yaml.golden
  internal/test/testdata/engine/case_14.yaml
  internal/test/testdata/engine/case_15.yaml
  internal/test/testdata/engine/case_16.yaml
  internal/test/testdata/server/plan_resources/plan_case_00.yaml
  internal/test/testdata/server/plan_resources/plan_case_01.yaml
  internal/test/testdata/server/plan_resources/plan_case_04.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_00.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_01.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_03.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_04.yaml
  internal/test/testdata/server/playground/proxy/pgp_rqp_case_05.yaml
  internal/test/testdata/store/derived_roles/derived_roles_01.yaml
  internal/test/testdata/store/resource_policies/policy_01.yaml
  internal/test/testdata/store/resource_policies/policy_06.yaml
  schema/jsonschema/cerbos/policy/v1/DerivedRoles.schema.json
  schema/jsonschema/cerbos/policy/v1/Policy.schema.json
  schema/jsonschema/cerbos/policy/v1/ResourcePolicy.schema.json
  schema/jsonschema/cerbos/policy/v1/ResourceRule.schema.json
  schema/jsonschema/cerbos/policy/v1/RoleDef.schema.json
  schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
Labels: enhancement

#945 enhancement: Configurable request limits
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/public/cerbos/request/v1/request.proto
  docs/modules/api/pages/index.adoc
  docs/modules/configuration/pages/server.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/server/conf.go
  internal/server/conf_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/svc/cerbos_svc.go
  internal/svc/playground_svc.go
  internal/test/testdata/server/checks/check_resource_batch/crb_invalid_case_03.yaml
  internal/test/testdata/server/checks/check_resource_batch/crb_invalid_case_04.yaml
  internal/test/testdata/server/checks/check_resource_set/crs_case_07.yaml
  internal/test/testdata/server/checks/check_resource_set/crs_invalid_case_02.yaml
  internal/test/testdata/server/checks/check_resource_set/crs_invalid_case_03.yaml
  internal/test/testdata/server/checks/check_resources/cr_invalid_case_03.yaml
  internal/test/testdata/server/checks/check_resources/cr_invalid_case_04.yaml
  schema/jsonschema/cerbos/request/v1/CheckResourceBatchRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourceBatchRequest/BatchEntry.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourceSetRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourcesRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourcesRequest/ResourceEntry.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundEvaluateRequest.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundProxyRequest.schema.json
  schema/jsonschema/cerbos/request/v1/ResourceSet.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#943 chore: Update telemetry schema
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .goreleaser.yml
  Makefile
  api/genpb/cerbos/telemetry/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry.pb.validate.go
  api/genpb/cerbos/telemetry/v1/telemetry_hashpb.pb.go
  api/genpb/cerbos/telemetry/v1/telemetry_vtproto.pb.go
  api/public/cerbos/telemetry/v1/telemetry.proto
  docs/modules/ROOT/pages/telemetry.adoc
  go.mod
  go.sum
  internal/telemetry/middleware.go
  internal/telemetry/middleware_test.go
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
  schema/jsonschema/cerbos/telemetry/v1/Event.schema.json
  schema/jsonschema/cerbos/telemetry/v1/Event/ApiActivity.schema.json
  schema/jsonschema/cerbos/telemetry/v1/Event/CountStat.schema.json
Labels: chore

#946 enhancement: Remove limit on number of roles
  api/genpb/cerbos/engine/v1/engine.pb.go
  api/genpb/cerbos/engine/v1/engine.pb.validate.go
  api/public/cerbos/engine/v1/engine.proto
  schema/jsonschema/cerbos/audit/v1/DecisionLogEntry.schema.json
  schema/jsonschema/cerbos/engine/v1/CheckInput.schema.json
  schema/jsonschema/cerbos/engine/v1/PlanResourcesRequest.schema.json
  schema/jsonschema/cerbos/engine/v1/Principal.schema.json
  schema/jsonschema/cerbos/policy/v1/Test.schema.json
  schema/jsonschema/cerbos/policy/v1/TestFixture/Principals.schema.json
  schema/jsonschema/cerbos/policy/v1/TestSuite.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourceBatchRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourceSetRequest.schema.json
  schema/jsonschema/cerbos/request/v1/CheckResourcesRequest.schema.json
  schema/jsonschema/cerbos/request/v1/PlanResourcesRequest.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundEvaluateRequest.schema.json
  schema/jsonschema/cerbos/request/v1/PlaygroundProxyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/ListAuditLogEntriesResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#947 chore(test): Update E2E test config for request limit tests
  e2e/blob/helmfile.yaml
  e2e/git/helmfile.yaml
  e2e/jaeger/helmfile.yaml
  e2e/mysql/helmfile.yaml
  e2e/postgres/helmfile.yaml
  e2e/sqlite/helmfile.yaml
  e2e/sqlserver/helmfile.yaml
Labels: testing, chore

#948 chore(deps): Bump github.com/opencontainers/runc from 1.1.0 to 1.1.2
  go.mod
  go.sum
Labels: chore

#949 chore(release): Add 0.17.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.17.0.adoc
Labels: chore, release

#950 docs: Update audit examples
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/conf.go
Labels: documentation

#952 fix: Apply defaults when loading audit config
  hack/dev/conf.insecure.yaml
  hack/dev/conf.secure.yaml
  hack/dev/plan.hurl
  hack/dev/requests/plan_resources/req1.json
  hack/dev/requests/plan_resources/req2.json
  internal/audit/conf.go
  internal/audit/conf_test.go
Labels: bug
