Repository cerbos/cerbos, pull requests merged in 2022-09, with the labels that each got.

#1199 chore(deps): Update buf modules
  api/public/buf.lock
Labels: chore

#1200 chore(deps): Private API buf mod update
  api/genpb/cerbos/engine/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/runtime/v1/hashpb_helpers.pb.go
  api/private/buf.lock
Labels: chore

#1198 fix: Query planner partially evaluates a lambda body
  internal/engine/planner.go
  internal/engine/testdata/ast_build_expr.yaml
  internal/test/testdata/query_planner/policies/principal_policy_macros.yaml
  internal/test/testdata/query_planner/suite/macro_user.yaml
Labels: bug

#1207 docs: Add clarification about who provides parentRoles
  docs/modules/policies/pages/derived_roles.adoc
Labels: documentation

#1202 enhancement: Allow specification of gRPC request metadata keys to be logged
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/conf.go
  internal/audit/interceptor.go
  internal/audit/interceptor_test.go
  internal/server/server.go
Labels: enhancement

#1208 docs(backport): Add clarification about who provides parentRoles (#1207)
  docs/modules/policies/pages/derived_roles.adoc
Labels: documentation

#1211 chore(docs): Fix git storage driver configuration example
  docs/modules/configuration/pages/storage.adoc
Labels: chore

#1210 fix(sdk): Allow plaintext connections to any host
  client/client.go
  client/client_test.go
  client/tests.go
  e2e/notls/helmfile.yaml
  e2e/notls/notls_test.go
  e2e/run.sh
  internal/server/tests.go
  internal/test/e2e/ctx.go
  internal/test/e2e/tests.go
Labels: bug

#1213 chore(test): Increase client timeout in E2E tests
  internal/test/e2e/tests.go
Labels: testing, chore

#1216 fix: Change the query planner handling of the condition "any"
  internal/engine/engine_test.go
  internal/engine/planner.go
  internal/test/testdata/query_planner/policies/derived_roles/beta.yaml
  internal/test/testdata/query_planner/policies/derived_roles/tiers.yaml
  internal/test/testdata/query_planner/policies/resource_policy_news.yaml
  internal/test/testdata/query_planner/suite/news_reader.yaml
Labels: bug

#1217 fix: Purge compile cache on store reload
  internal/compile/manager.go
  internal/storage/db/internal/db.go
  internal/storage/db/store.go
  internal/storage/git/store.go
  internal/storage/index/index.go
  internal/storage/store.go
Labels: bug

#1218 enhancement: Advanced server configuration
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/server/conf.go
  internal/server/server.go
  internal/server/server_test.go
Labels: enhancement

#1237 chore(deps): Update go.opentelemetry.io/otel/bridge/opencensus to 0.32.1
  go.mod
  go.sum
Labels: chore

#1236 chore(ci): Run Go vulnerability check periodically
  .github/workflows/vulnerability-check.yaml
Labels: ci, chore

#1235 enhancement: Group compile requests
  Makefile
  internal/audit/interceptor.go
  internal/compile/manager.go
  internal/compile/manager_test.go
  internal/engine/engine.go
  internal/observability/tracing/attributes.go
Labels: enhancement

#1245 docs: Fix usage of CEL matches operator
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#1247 docs(backport): Fix usage of CEL matches operator (#1245)
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#1248 chore(deps): Update alpine base image from 3.15 to 3.16
  Dockerfile.cerbos
  Dockerfile.cerbosctl
Labels: chore

#1250 chore(helm): Allow configuring a custom nodePort in helm chart values
  deploy/charts/cerbos/templates/service.yaml
  deploy/charts/cerbos/values.yaml
Labels: chore

#1251 docs: Make optionality of Scoped Policies more explicit
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/scoped_policies.adoc
Labels: documentation

#1253 docs(backport): Make optionality of Scoped Policies more explicit (#1251)
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/scoped_policies.adoc
Labels: documentation

#1255 feat: Temporary log level change with USR1 signal
  cmd/cerbos/run/run.go
  cmd/cerbos/server/server.go
  internal/observability/logging/logging.go
  internal/test/test.go
Labels: feature

#1256 fix: Treat non-boolean expression results as `false`
  internal/engine/evaluator.go
  internal/test/testdata/cel_eval/null_attr_allof.yaml
  internal/test/testdata/cel_eval/null_attr_anyof.yaml
  internal/test/testdata/cel_eval/null_attr_noneof.yaml
Labels: bug
