Repository cerbos/cerbos, pull requests merged in 2023-07, with the labels that each got.

#1675 chore(e2e): Run govulncheck without verbose flag
  .github/workflows/vulnerability-check.yaml
Labels: kind/chore

#1693 enhancement(helm): Add config checksum to pod annotations so that deployment restarts on config changes
  deploy/charts/cerbos/templates/_helpers.tpl
Labels: kind/enhancement, area/deployment

#1705 chore(docs): Ignore PlaygroundEnabled configuration flag
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/server/conf.go
Labels: area/documentation

#1686 feat: Add cerbosctl command to export policies and schemas from store
  api/genpb/cerbos/request/v1/request.pb.go
  api/public/cerbos/request/v1/request.proto
  cmd/cerbosctl/root/root.go
  cmd/cerbosctl/store/export/export.go
  cmd/cerbosctl/store/export/internal/exporter.go
  cmd/cerbosctl/store/export/internal/exporter_test.go
  cmd/cerbosctl/store/export/internal/testdata/scope.txt
  cmd/cerbosctl/store/export/internal/testdata/single_policy.txt
  cmd/cerbosctl/store/export/internal/testdata/single_schema.txt
  cmd/cerbosctl/store/reload/reload.go
  cmd/cerbosctl/store/store.go
  docs/modules/cli/pages/cerbosctl.adoc
  internal/policy/policy.go
  internal/storage/index/schema.go
  internal/test/txtar.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: kind/feature
