Repository cerbos/cerbos, pull requests merged in 2023-04, with the labels that each got.

#1515 chore: Ignore stdout/stderr sync errors in audit log
  internal/audit/file/log.go
Labels: chore

#1516 fix: Kafka async produce context cancellation
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  go.mod
  go.sum
  internal/audit/kafka/conf.go
  internal/audit/kafka/kafka_test.go
  internal/audit/kafka/publisher.go
Labels: bug

#1508 feat: Add JUnit output format for test results
  api/genpb/cerbos/policy/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/public/cerbos/policy/v1/policy.proto
  cmd/cerbos/compile/compile.go
  cmd/cerbos/compile/errors/errors.go
  cmd/cerbos/compile/internal/compilation/display.go
  cmd/cerbos/compile/internal/flagset/format.go
  cmd/cerbos/compile/internal/lint/display.go
  cmd/cerbos/compile/internal/verification/display.go
  cmd/cerbos/main.go
  docs/modules/cli/pages/cerbos.adoc
  internal/policy/policy.go
  internal/test/testdata/verify/cases/case_001.yaml.golden
  internal/test/testdata/verify/cases/case_002.yaml.golden
  internal/test/testdata/verify/cases/case_003.yaml
  internal/test/testdata/verify/cases/case_003.yaml.golden
  internal/test/testdata/verify/cases/case_004.yaml
  internal/test/testdata/verify/cases/case_004.yaml.golden
  internal/test/testdata/verify/cases/case_005.yaml
  internal/test/testdata/verify/cases/case_005.yaml.golden
  internal/test/testdata/verify/cases/case_006.yaml
  internal/test/testdata/verify/cases/case_006.yaml.golden
  internal/test/testdata/verify/cases/case_007.yaml
  internal/test/testdata/verify/cases/case_007.yaml.golden
  internal/test/testdata/verify/cases/case_008.yaml.golden
  internal/test/testdata/verify/cases/case_009.yaml.golden
  internal/test/testdata/verify/cases/case_010.yaml.golden
  internal/test/testdata/verify_junit/cases/case_001.yaml
  internal/test/testdata/verify_junit/cases/case_001.yaml.golden
  internal/test/testdata/verify_junit/cases/case_001.yaml.input
  internal/test/testdata/verify_junit/cases/case_002.yaml
  internal/test/testdata/verify_junit/cases/case_002.yaml.golden
  internal/test/testdata/verify_junit/cases/case_002.yaml.input
  internal/test/testdata/verify_junit/cases/case_003.yaml
  internal/test/testdata/verify_junit/cases/case_003.yaml.golden
  internal/test/testdata/verify_junit/cases/case_003.yaml.input
  internal/test/testdata/verify_junit/cases/case_004.yaml
  internal/test/testdata/verify_junit/cases/case_004.yaml.golden
  internal/test/testdata/verify_junit/cases/case_004.yaml.input
  internal/test/testdata/verify_junit/cases/case_005.yaml
  internal/test/testdata/verify_junit/cases/case_005.yaml.golden
  internal/test/testdata/verify_junit/cases/case_005.yaml.input
  internal/test/testdata/verify_junit/store/company.yaml
  internal/verify/junit/junit.go
  internal/verify/junit/junit_test.go
  internal/verify/test_fixture.go
  internal/verify/verify.go
  schema/jsonschema/cerbos/policy/v1/TestResults.schema.json
  schema/jsonschema/cerbos/policy/v1/TestResults/Suite.schema.json
  schema/jsonschema/cerbos/response/v1/PlaygroundTestResponse.schema.json
  schema/jsonschema/cerbos/response/v1/PlaygroundTestResponse/TestResults.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement, feature

#1520 enhancement: Add principal, resource and action as properties of JUnit output
  internal/test/testdata/verify_junit/cases/case_001.yaml.golden
  internal/test/testdata/verify_junit/cases/case_003.yaml.golden
  internal/test/testdata/verify_junit/cases/case_004.yaml.golden
  internal/verify/junit/junit.go
Labels: enhancement

#1528 docs: Document CEL string.format function
  docs/modules/policies/pages/conditions.adoc
Labels: documentation

#1531 chore: Publish unstable API to BSR
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  api/private/buf.lock
  api/private/buf.yaml
  api/public/buf.lock
  schema/jsonschema/cerbos/engine/v1/PlanResourcesAst.schema.json
  schema/jsonschema/cerbos/engine/v1/PlanResourcesAst/LogicalOperation.schema.json
  schema/jsonschema/cerbos/engine/v1/PlanResourcesAst/Node.schema.json
Labels: chore

#1533 fix: Prevent default config from being turned into a path
  cmd/cerbos/server/server.go
Labels: bug

#1532 chore(release): Add 0.26.0 release notes
  docs/modules/cli/pages/cerbos.adoc
  docs/modules/configuration/pages/storage.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.26.0.adoc
Labels: chore, release

#1526 feat: Validate policy and test files with JSON schema
  cmd/cerbos/compile/compile.go
  go.mod
  internal/audit/conf.go
  internal/jsonschema/jsonschema.go
  internal/storage/conf.go
  internal/storage/index/builder.go
  internal/test/testdata/index/corrupt_files.yaml
  internal/test/testdata/index/incomplete_files.yaml
  internal/test/testdata/server/playground/evaluate/pge_invalid_case_01.yaml
  internal/test/testdata/server/playground/test/pgt_invalid_case_01.yaml
  internal/test/testdata/server/playground/test/pgt_invalid_case_02.yaml
  internal/test/testdata/server/playground/validate/pgv_invalid_case_01.yaml
  internal/test/testdata/store/derived_roles/common_roles.yaml
  internal/test/testdata/store_archive/policies.tar
  internal/test/testdata/store_archive/policies.tgz
  internal/test/testdata/store_archive/policies.zip
  internal/test/testdata/verify/cases/case_004.yaml.golden
  internal/test/testdata/verify/cases/case_005.yaml.golden
  internal/test/testdata/verify/cases/case_007.yaml.golden
  internal/verify/verify.go
  schema/schema.go
Labels: enhancement, feature

#1541 fix: Introduce custom temp directory creation function with pathname length limit for uds
  internal/server/server_test.go
Labels: bug

#1550 enhancement: Handle schemas folder being in wrong place with more verbose error
  internal/storage/index/builder.go
  internal/test/testdata/index/schemas_in_valid_dir.yaml
  internal/test/testdata/index/schemas_in_wrong_dir.yaml
  internal/test/testdata/index/schemas_prepended_dir.yaml
Labels: enhancement

#1552 docs(backport): Clarify policy repository layout (#1551)
  docs/modules/policies/pages/best_practices.adoc
  docs/modules/policies/pages/compile.adoc
Labels: documentation
