Repository cerbos/cerbos, pull requests merged in 2023-03, with the labels that each got.

#1478 docs(backport): Fix typo in 04_testing-policies.adoc (#1477)
  docs/modules/ROOT/pages/tutorial/04_testing-policies.adoc
Labels: documentation

#1481 docs: Fix name of test output format flag
  docs/modules/policies/pages/compile.adoc
Labels: documentation

#1482 docs(backport): Fix name of test output format flag (#1481)
  docs/modules/policies/pages/compile.adoc
Labels: documentation

#1473 enhancement: Add support for reading archive files for the disk driver
  .gitattributes
  cmd/cerbos/compile/compile.go
  cmd/cerbosctl/put/internal/files/find.go
  docs/modules/configuration/pages/storage.adoc
  go.mod
  go.sum
  internal/storage/disk/disk.go
  internal/storage/index/builder_test.go
  internal/storage/index/index_test.go
  internal/test/testdata/store_archive/policies.tar
  internal/test/testdata/store_archive/policies.tgz
  internal/test/testdata/store_archive/policies.zip
  internal/util/filesystem.go
  internal/util/filesystem_test.go
Labels: enhancement

#1487 chore: Make Otel resource schemaless
  internal/observability/tracing/tracing.go
Labels: chore

#1488 docs: Add resource ID to test examples
  docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/company_test.yaml
  docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/contact_test.yaml
Labels: documentation

#1491 docs(backport): Add resource ID to test examples (#1488)
  docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/company_test.yaml
  docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/contact_test.yaml
Labels: documentation

#1501 enhancement: Report audit close error
  internal/audit/file/log.go
  internal/audit/file/log_test.go
  internal/audit/local/badgerdb.go
  internal/audit/log.go
  internal/server/server.go
Labels: enhancement

#1499 feat: Kafka audit log
  docs/modules/configuration/partials/fullconfiguration.adoc
  go.mod
  go.sum
  internal/audit/kafka/conf.go
  internal/audit/kafka/marshal_test.go
  internal/audit/kafka/publisher.go
  internal/audit/kafka/publisher_test.go
  internal/server/server.go
Labels: enhancement, feature

#1506 docs: Add Kafka audit backend docs
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/kafka/conf.go
  internal/audit/kafka/publisher.go
Labels: documentation

#1505 chore(ci): Add timeouts to workflows
  .github/workflows/cache.yaml
  .github/workflows/codeql.yml
  .github/workflows/docs.yaml
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/pr-title.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  .github/workflows/vulnerability-check.yaml
Labels: ci, chore

#1509 chore(ci): Increase snapshot build timeout
  .github/workflows/snapshot.yaml
Labels: ci, chore

#1510 fix: Kafka async publish fails when the API request returns
  docs/modules/configuration/pages/audit.adoc
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/audit/kafka/conf.go
  internal/audit/kafka/publisher.go
Labels: bug
