Repository cerbos/cerbos, pull requests merged in 2023-09, with the labels that each got.

#1738 chore(ci): Use experimental 'loopvar' released with Go 1.21
  .github/actions/setup-go/action.yaml
  .github/workflows/pr-test.yaml
  Makefile
Labels: area/ci, kind/chore

#1779 docs: Add testdata schema URLs
  docs/modules/policies/pages/authoring_tips.adoc
  docs/modules/policies/pages/compile.adoc
Labels: area/documentation

#1787 chore(deps): Downgrade pterm to v0.12.66
  go.mod
  go.sum
Labels: kind/chore, area/dependencies
