Repository cerbos/cerbos, pull requests merged in 2023-01, with the labels that each got.

#1401 fix: Fix handling of the SIGUSR1 on Windows
  internal/observability/logging/logging.go
  internal/observability/logging/signal.go
  internal/observability/logging/signal_windows.go
Labels: bug

#1406 fix: Handle principal-policy-only cases
  cmd/cerbosctl/put_test.go
  internal/engine/engine.go
  internal/storage/blob/cloner_test.go
  internal/storage/index/builder_test.go
  internal/test/testdata/engine/case_17.yaml
  internal/test/testdata/store/principal_policies/policy_03.yaml
Labels: bug

#1405 enhancement: Add wrapper function for `sqlx.Connect` call, incorporating basic retries
  go.mod
  internal/storage/db/internal/funcs.go
  internal/storage/db/internal/funcs_test.go
  internal/storage/db/mysql/mysql.go
  internal/storage/db/postgres/postgres.go
  internal/storage/db/sqlite3/sqlite3.go
  internal/storage/db/sqlserver/sqlserver.go
Labels: enhancement

#1415 chore(release): Add 0.24.0 release notes
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.24.0.adoc
Labels: chore, release

#1418 chore: Add licence file for pjbgf/sha1cd
  hack/notice/overrides/licences/github.com/pjbgf/sha1cd/LICENSE
Labels: chore

#1420 chore(ci): Update gcloud auth
  .github/workflows/release.yaml
Labels: ci, chore

#1427 chore(deps): Revert update of github.com/jackc/pgx/v4 to v5 (#1425)
  go.mod
  go.sum
  internal/storage/db/postgres/postgres.go
  internal/storage/db/postgres/postgres_test.go
Labels: chore, dependencies

#1430 docs: Add policyVersion example to tests
  docs/modules/policies/pages/compile.adoc
Labels: documentation

#1426 feat: Admin API endpoint to disable policy(s)
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/request.pb.go
  api/genpb/cerbos/request/v1/request.pb.validate.go
  api/genpb/cerbos/request/v1/request_hashpb.pb.go
  api/genpb/cerbos/request/v1/request_vtproto.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_hashpb.pb.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/genpb/cerbos/svc/v1/svc_grpc.pb.go
  api/public/cerbos/request/v1/request.proto
  api/public/cerbos/response/v1/response.proto
  api/public/cerbos/svc/v1/svc.proto
  client/admin.go
  cmd/cerbosctl/disable/disable.go
  cmd/cerbosctl/disable/disable_test.go
  cmd/cerbosctl/disable/internal/policy/policy.go
  cmd/cerbosctl/disable/policy.go
  cmd/cerbosctl/root/root.go
  docs/modules/api/pages/admin_api.adoc
  docs/modules/cli/pages/cerbosctl.adoc
  internal/compile/manager_test.go
  internal/storage/db/internal/db.go
  internal/storage/db/internal/model.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  schema/jsonschema/cerbos/request/v1/DisablePolicyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/DisablePolicyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: feature
