Repository cerbos/cerbos, pull requests merged in 2023-02, with the labels that each got.

#1433 docs: Clarify how to provide blob store credentials
  docs/modules/configuration/pages/storage.adoc
Labels: documentation

#1435 docs(backport): Clarify how to provide blob store credentials (#1433)
  docs/modules/configuration/pages/storage.adoc
Labels: documentation

#1434 docs(backport): Add policyVersion example to tests (#1430)
  docs/modules/policies/pages/compile.adoc
Labels: documentation

#1436 fix: Evict disabled policy from the cache
  internal/compile/manager.go
Labels: bug

#1440 chore(ci): Use Go 1.20 in CI
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snaphot.yaml
  .github/workflows/test-matrix.yaml
  .github/workflows/vulnerability-check.yaml
  client/client_test.go
  cmd/cerbosctl/audit/audit.go
  cmd/cerbosctl/decisions/decisions.go
  internal/conditions/cerbos_lib_benchmarks_test.go
  internal/engine/planner/ast.go
  internal/printer/printer.go
Labels: ci, chore

#1439 fix: Evict policies that are changed in-place
  docs/modules/configuration/partials/fullconfiguration.adoc
  internal/compile/conf.go
  internal/compile/manager.go
  internal/storage/git/store.go
  internal/storage/git/store_test.go
  internal/storage/index/index.go
  internal/storage/store.go
Labels: bug

#1441 enhancement: Prevent scoped policies being disabled
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/public/cerbos/response/v1/response.proto
  client/admin.go
  cmd/cerbosctl/disable/disable_test.go
  cmd/cerbosctl/disable/internal/policy/policy.go
  internal/compile/manager_test.go
  internal/storage/db/internal/db.go
  internal/storage/db/store.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  schema/jsonschema/cerbos/response/v1/DisablePolicyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement

#1444 chore: Upgrade Otel semconv version
  e2e/run.sh
  internal/observability/tracing/tracing.go
  internal/observability/tracing/tracing_test.go
Labels: chore

#1447 fix: Fix erroneous check in the Disable command
  cmd/cerbosctl/disable/disable_test.go
  internal/storage/db/internal/db.go
Labels: bug

#1448 feat: Add Cerbos version to response headers
  internal/server/middleware.go
  internal/server/server.go
Labels: feature

#1445 enhancement!: Return number of schemas deleted, and don't error if none
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/response.pb.go
  api/genpb/cerbos/response/v1/response.pb.validate.go
  api/genpb/cerbos/response/v1/response_hashpb.pb.go
  api/genpb/cerbos/response/v1/response_vtproto.pb.go
  api/public/cerbos/response/v1/response.proto
  internal/storage/db/internal/db.go
  internal/storage/db/internal/tests.go
  internal/storage/store.go
  internal/svc/admin_svc.go
  schema/jsonschema/cerbos/response/v1/DeleteSchemaResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: enhancement, breaking

#1423 docs: Add note on resource-led policy design in `Best practices` section
  docs/modules/policies/pages/best_practices.adoc
Labels: documentation

#1446 chore(ci): Improve caching
  .github/actions/setup-go/action.yaml
  .github/workflows/cache.yaml
  .github/workflows/e2e.yaml
  .github/workflows/pr-test.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  .github/workflows/test-matrix.yaml
  .github/workflows/vulnerability-check.yaml
  Makefile
Labels: ci, chore

#1454 fix: Fix typo in policy metadata field
  api/genpb/cerbos/policy/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/public/cerbos/policy/v1/policy.proto
  client/admin_test.go
  cmd/cerbosctl/get/internal/policy/policy.go
  cmd/cerbosctl/get/internal/policy/sort.go
  cmd/cerbosctl/get/internal/policy/sort_test.go
  internal/policy/policy.go
  internal/policy/policy_test.go
  internal/storage/db/internal/tests.go
  internal/storage/index/index_test.go
  schema/jsonschema/cerbos/policy/v1/Metadata.schema.json
  schema/jsonschema/cerbos/policy/v1/Policy.schema.json
  schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: bug

#1458 fix: Fix typo in policy metadata field
  api/genpb/cerbos/policy/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.go
  api/genpb/cerbos/policy/v1/policy.pb.validate.go
  api/genpb/cerbos/policy/v1/policy_vtproto.pb.go
  api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
  api/genpb/cerbos/response/v1/hashpb_helpers.pb.go
  api/public/cerbos/policy/v1/policy.proto
  client/admin_test.go
  cmd/cerbosctl/get/internal/policy/policy.go
  cmd/cerbosctl/get/internal/policy/sort.go
  cmd/cerbosctl/get/internal/policy/sort_test.go
  internal/policy/policy.go
  internal/policy/policy_test.go
  internal/storage/db/internal/tests.go
  internal/storage/index/index_test.go
  schema/jsonschema/cerbos/policy/v1/Metadata.schema.json
  schema/jsonschema/cerbos/policy/v1/Policy.schema.json
  schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
  schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: bug

#1459 enhancement: Add DeleteSchema RPC to the SDK AdminClient
  client/admin.go
Labels: enhancement

#1460 chore(release): Add 0.25.0 release notes
  docs/modules/api/pages/admin_api.adoc
  docs/modules/releases/nav.adoc
  docs/modules/releases/pages/v0.25.0.adoc
Labels: chore, release

#1462 enhancement!: Make config flag optional
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  .goreleaser.yml
  Dockerfile.cerbos
  Makefile
  cmd/cerbos/healthcheck/healthcheck.go
  cmd/cerbos/server/server.go
  docs/modules/configuration/pages/index.adoc
  internal/config/conf.yaml.gotmpl
  internal/config/config.go
  internal/config/config_test.go
  internal/storage/disk/disk.go
Labels: enhancement

#1464 enhancement: Enable auth on API explorer page
  schema/assets/ui.html
Labels: enhancement

#1467 chore: Remove Playground from API explorer
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/public/cerbos/svc/v1/svc.proto
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: chore

#1469 docs: Document /api/server_info
  docs/modules/api/pages/index.adoc
Labels: documentation

#1470 docs(backport): Document /api/server_info (#1469)
  docs/modules/api/pages/index.adoc
Labels: documentation

#1471 chore(api): Remove api/x/plan/resources endpoint
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/public/cerbos/svc/v1/svc.proto
  hack/dev/plan.hurl
  internal/server/tests.go
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: chore, api

#1476 chore: Deprecate old policy disable endpoint
  api/genpb/cerbos/svc/v1/svc.pb.go
  api/genpb/cerbos/svc/v1/svc.pb.gw.go
  api/public/cerbos/svc/v1/svc.proto
  docs/modules/api/pages/admin_api.adoc
  schema/openapiv2/cerbos/svc/v1/svc.swagger.json
Labels: chore
