Repository cerbos/cerbos, pull requests merged in 2024-03, with the labels that each got.

#2037 chore(ci): Fix disk space problem in Publish Dev Containers job
  .github/workflows/snapshot.yaml
Labels: area/ci, kind/chore

#2039 docs: Add fly.io deploy guide
  docs/modules/configuration/pages/index.adoc
  docs/modules/configuration/pages/server.adoc
  docs/modules/deployment/nav.adoc
  docs/modules/deployment/pages/cloud-platforms.adoc
Labels: area/documentation, kind/chore

#2057 docs: Embed tutorial videos
  docs/modules/recipes/pages/authentication/aws-cognito/index.adoc
  docs/modules/recipes/pages/authentication/fusionauth/index.adoc
  docs/modules/recipes/pages/authentication/okta/index.adoc
Labels: area/documentation

#2069 chore(docs): Improve documentation accessibility
  docs/supplemental-ui/css/site-extra.css
Labels: area/documentation, kind/chore

#2070 docs(backport): Improve documentation accessibility (#2069)
  docs/supplemental-ui/css/site-extra.css
Labels: area/documentation, kind/chore
